### ISSUE TITLE
Producing incorrect ordinal values - 1th, 2th and 3th

### ISSUE THREAD

**Issue by avioli** [Byron/gitoxide#1023]
### Current behavior 😯

Running `gix revision explain ...` produces funny ordinal values like 1th, 2th and 3th.

```
$ gix r explain @~1
01. Lookup the 'HEAD' reference
02. Traverse to the 1th ancestor of revision named 'HEAD'
$ gix r explain @~2
01. Lookup the 'HEAD' reference
02. Traverse to the 2th ancestor of revision named 'HEAD'
$ gix r explain @~3
01. Lookup the 'HEAD' reference
02. Traverse to the 3th ancestor of revision named 'HEAD'
```

### Expected behavior 🤔

```
$ gix r explain @~1
01. Lookup the 'HEAD' reference
02. Traverse to the 1st ancestor of revision named 'HEAD'
$ gix r explain @~2
01. Lookup the 'HEAD' reference
02. Traverse to the 2nd ancestor of revision named 'HEAD'
$ gix r explain @~3
01. Lookup the 'HEAD' reference
02. Traverse to the 3rd ancestor of revision named 'HEAD'
```

**Comment by avioli** [comment]
Offending lines:

https://github.com/Byron/gitoxide/blob/c270f7883e1ea8156d521b12d161a47b2144425c/gitoxide-core/src/repository/revision/explain.rs#L132-L133

**Comment by Byron** [comment]
Thanks for posting. I was aware when writing this, knowing that one day it will be changed when internationalisation is added. For now, I changed `th` to `.` as it is probably less offensive when reading it.
