### ISSUE TITLE
Shell completion for zsh registers incorrectly

### ISSUE THREAD

**Issue by tranzystorek-io** [Byron/gitoxide#1060]
### Current behavior 😯

The completion script generated by `gix generate-completions --shell zsh` ends up with a `#compdef gitoxide` header instead of `#compdef gix`, and so is registered for the nonexistent `gitoxide` command.

This is because the `clap_complete::generate` invocation expects the actual binary name, but gets `env!("CARGO_PKG_NAME")` instead.

### Expected behavior 🤔

Shell completion script is properly formed.

**Comment by Byron** [comment]
Thanks a lot for reporting!

Admittedly, I never tried them and assume it would pick up the binary name just like `gix --version` does (it knows its binary name).

CC @ShaunSHamilton - can you help?

**Comment by tranzystorek-io** [comment]
Probably just a quick fix to do similar to what `clap_complete` docs suggest:

```rust
fn print_completions<G: Generator>(gen: G, cmd: &mut Command) {
    generate(gen, cmd, cmd.get_name().to_string(), &mut io::stdout());
}
```

**Comment by Byron** [comment]
I am looking forward to a PR :). Thanks so much.

**Comment by ShaunSHamilton** [comment]
Something else we changed between reviews was:

```rust
            let bin_name = "gix";

            app.set_bin_name(bin_name);
```
