### ISSUE TITLE
The error variant "Could initialize the http client" provides no further detail

### ISSUE THREAD

**Issue by Shnatsel** [Byron/gitoxide#1075]
### Current behavior 😯

Users of `cargo audit` are reporting that they see an error "Could initialize the http client" with no further detail: https://github.com/rustsec/rustsec/issues/1029 
This makes it non-actionable for users and impossible to debug for developers.

It is defined in this code:
https://github.com/Byron/gitoxide/blob/c0e72fbadc0a494f47a110aebb46462d7b9f5664/gix-transport/src/client/blocking_io/http/traits.rs#L6-L10

### Expected behavior 🤔

First off, the message should include a "not" :wink: 

The `Display` implementation for the error should also call the `Display` of the underlying error, so that the cause of the failed initialization could be understood and acted upon.

**Comment by Shnatsel** [comment]
As a wild guess, perhaps changing

```rust
    #[error("Could not initialize the http client")]
    InitHttpClient {
        source: Box<dyn std::error::Error + Send + Sync + 'static>,
    },
```
to
```rust
    #[error("Could not initialize the http client: {source}")]
    InitHttpClient {
        source: Box<dyn std::error::Error + Display + Send + Sync + 'static>,
    },
```
would do the trick?

But I am not familiar with `thiserror` so please take this with a grain of salt.

**Comment by Byron** [comment]
Thanks for letting me know about this missing word.

For good measure I assured `thiserror` is working as advertised and added this passing test.

```
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn http_error_has_source() {
        assert!(std::error::Error::source(&Error::InitHttpClient {
            source: Box::new(Error::Detail {
                description: "something".into()
            })
        })
        .is_some());
    }
}
```

If `source()` is used to generate errors, these will be displayed. `anyhow` will do that for instance.
Error messages that concatenate their source in the error messages aren't used in `gix`, instead it relies on a `source()` trail which is maintained by `thiserror` automatically.

I hope that helps.
