### ISSUE TITLE
Donating Funds to Gitoxide

### ISSUE THREAD

**Issue by Lfada** [Byron/gitoxide#1086]
### Summary 💡

Hi Gitoxide, I'm Lucas, a core contributor to the Radworks project. https://radworks.org/

[[Radicle](http://www.radicle.xyz/)] has been using https://github.com/Byron/gitoxide. It's in fact one of our most critical dependencies!

All Radicle’s core-contributors really appreciate the work you all do and we want to make sure that you are all well-funded to keep doing it. For that reason, we have decided to donate some funds to your project through [[Drips](https://www.drips.network/)](an initiative that is coming out of our organization for funding FOSS).

Who can I talk to about it?

### Motivation 🔦

Finding the right person to talk to. The goal is to answer any questions they have, and share more details. 

cc: @Byron @edward-shen @svetli-n

**Comment by Lfada** [comment]
Sure thing @Byron 

This video can also help you understand the claim process: https://www.youtube.com/watch?v=AOl_XkgWv-A 

We would be grateful if someone from Gitoxide jumps on a call with us, we recently released and trying to find the best solution for FOSS projects and their recipients to receive recurring funds. Any feedback, ideas, and questions are welcome.

**Comment by Byron** [comment]
You can send an email to my public email address here on GitHub and I will provide you with a link that makes scheduling easy, happy to help as "most naive user who probably knows nothing yet" :).

**Comment by Byron** [comment]
I have gone through the process now and can definitely say that it works 🎉! Diligently I took notes with feedback and insights that I would love to share with you on our call as well, can't wait :).
