### ISSUE TITLE
`git-prompt` assumes it can interact with `/dev/tty`

### ISSUE THREAD

**Issue by bittrance** [Byron/gitoxide#1090]
### Current behavior 😯

Cloning a non-public GitHub repo with gix will ask for username/password even if stdin is not a tty:
```
$ cargo run -- --url https://github.com/bittrance/verrah-secret --action /bin/ls < /dev/null
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/kitops --url 'https://github.com/bittrance/verrah-secret' --action /bin/ls`
Username for https://github.com:
```

### Expected behavior 🤔

I would have expected an error when `gix-prompt`s Unix built-in prompter encountered a non-tty stdin. It seems that a gix-based program running in a container or similar would stall forever if you misspell the repo URL. But maybe I don't understand all the cases where you may want terminal-based prompting?

If you agree, I'll be happy to provide a PR.

### Steps to reproduce 🕹

```
git clone https://github.com/bittrance/kitops
cd kitops
cargo run -- --url https://github.com/bittrance/verrah-secret --action /bin/ls 
```

**Comment by Byron** [comment]
At least I believe that I modelled the behaviour after `git` and it writes to `/dev/tty` directly, so it doesn't have to care, in theory, about stdin actually pointing to a TTY.

Can you shed some light about what `git` does in this case? If it does the same, I'd deem it acceptable to be compatible with it, even though it seems one can do better here. But if `git` already does better, then this is definitely something to fix, and we can figure something out.

Thanks for offering to help, it's much appreciated!

**Comment by bittrance** [comment]
It would indeed seem Git does the same. I find this a bit strange, but perhaps there are some valid scenarios where prompting is needed when stdin is redirected? Anyway, the more common case is that there is no accessible tty at all, in which case both gix and git fails with "no such device or address". This addresses my most important issue, namely avoiding mysterious hangs.

In my case, non-interactive execution is the norm, so I'll implement something at my end.

**Comment by Byron** [comment]
There is actually an environment variable which can turn off the prompting: `GIT_TERMINAL_PROMPT=0`.
It might also be possible to detect such environments, i.e. where the TTY isn't part of a user-terminal, but that would probably be another story.

However, `gitoxide` is in a position to eventually improve on certain behaviours if there is enough demand and if it makes sense. The same goes for `git` itself, it's actually quite straightforward to interact with the mailing list and make contributions.

**Comment by bittrance** [comment]
Actually, closing the issue might have been premature. It seems there is no simple way for a program that uses gitoxide as a lib to disable [internal prompting](https://github.com/Byron/gitoxide/blob/e47c46d4eeff144bc4c30c488161859318cd90a6/gix-credentials/src/helper/cascade.rs#L125)? Using an environment variable is fiddly and not ideal since it is not thread-safe. I'm thinking I would need a config var that allows setting prompt to `Disabled` here: https://github.com/Byron/gitoxide/blob/e47c46d4eeff144bc4c30c488161859318cd90a6/gix/src/config/snapshot/credential_helpers.rs#L147 ? Something like `gitoxide.credentials.builtinPrompt` perhaps?

**Comment by Byron** [comment]
Yes, I agree, and it's something I definitely want to see implemented as well, as it's a perfect example where `git` is a bit lacking as it doesn't have a configuration flag for it (probably because they didn't need it yet).
