### ISSUE TITLE
pixelmatch-py.git cannot be cloned with gix clone

### ISSUE THREAD

**Issue by gl-yziquel** [Byron/gitoxide#1129]
### Current behavior 😯

I tried to clone the pixelmatch-py.git repository on github. Here: https://github.com/whtsky/pixelmatch-py.git

It fails with Error: Process handshake with command "/bin/sh" "-c" "git-lfs filter-process" "--" failed

### Expected behavior 🤔

Ideally, the git repository should get cloned, like all the other repositories that I've cloned with gix. (Thank you very much for that tool.)

### Git behavior

The clone succeeds.

### Steps to reproduce 🕹

Just clone. And see it fail.

**Comment by Byron** [comment]
Thanks a lot for letting me know! I could already reproduce a couple of issues related to git filter support, even though none of them is yours.

> It fails with Error: Process handshake with command "/bin/sh" "-c" "git-lfs filter-process" "--" failed

Can it be that you are running this on windows? If so, the latest version from `main` should get you past this issue at least even though #1130 will probably be needed to make it all work.

It's strange that `git lfs` seems to work slightly differently and runs in to failures, even though I use it in `gitoxide` too, and there it works fine. I am looking forward to solve this issue :).

**Comment by gl-yziquel** [comment]
No. I'm on a linux box.

**Comment by Byron** [comment]
Oh, that's interesting! 

Could you share the output of `gix config filter`?

Here is mine, and with it I am not running into the issue described here.

```
❯ gix config filter
# From '/Users/byron/.gitconfig' (User)
[filter "lfs"]
        required = true
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
```

While at it, please also provide the version of `git-lfs`:

```
❯ git-lfs --version
git-lfs/3.4.0 (GitHub; darwin arm64; go 1.20.6)
```

Thanks again!

**Comment by gl-yziquel** [comment]
Here:

```console
mini-me@virtucon ~> gix config filter
Error: Could not find a git repository in '.' or in any of its parents within device limits below '/home'
```

```console
mini-me@virtucon ~ [1]> git-lfs --version
git-lfs/3.3.0 (GitHub; linux amd64; go 1.18.1; git e6f011be)
```

I built `gix` by running `cargo build` on revision `d257099bb87428986d1630d29b6d47430454e275`. I'm using the binary generated in `target/debug`.

**Comment by Byron** [comment]
Thanks! `git-lfs` seems new enough to assume that's not part of the problem.

Can you retry `gix config filter` from within a repository please? For now it can't work without a repo.

**Comment by gl-yziquel** [comment]
Here:

```console
mini-me@virtucon ~/h/c/webob (main)> gix config filter
# From '/home/yziquel/.gitconfig' (GitInstallation)
[filter "lfs"]
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
        clean = git-lfs clean -- %f
```

**Comment by Byron** [comment]
It appears that the options are the same as mine.

Looking at the [error definition itself](https://github.com/Byron/gitoxide/blob/a063c62e3a30006d837b267e2ce74e70e48b4fb6/gix-filter/src/driver/init.rs#L20-L24) I see that the error presented here is lacking a source.

Would you post the whole error here as well?

**Comment by gl-yziquel** [comment]
Sorry. I only have this output:

```console
mini-me@virtucon ~/mud> gix clone https://github.com/whtsky/pixelmatch-py.git
 19:20:19 indexing done 735.0 objects in 0.05s (15.1k objects/s)
 19:20:19 decompressing done 581.2KB in 0.05s (11.9MB/s)
 19:20:19     Resolving done 735.0 objects in 0.15s (4.9k objects/s)
 19:20:19      Decoding done 4.4MB in 0.15s (28.9MB/s)
 19:20:19 writing index file done 21.7KB in 0.00s (90.9MB/s)
 19:20:19  create index file done 735.0 objects in 0.20s (3.7k objects/s)
 19:20:19          read pack done 321.5KB in 0.23s (1.4MB/s)
Error: Process handshake with command "/bin/sh" "-c" "git-lfs filter-process" "--" failed

Caused by:
    0: Failed to read or write to the process
    1: Failed to decode the first four hex bytes indicating the line length: Invalid character
yziquel@hilbert ~/mud [1]> 

```

**Comment by Byron** [comment]
Thanks! Very helpful, even though it doesn't show much more.

What happens if you execute/run `git-lfs` just like that? Does it work? My guess would be that it fails to launch the command. If so, does `git lfs` work?

If it runs fine, are you aware of any configuration that might affect `git-lfs`?

From what I see, it manages to launch the program, but it doesn't respond according to protocol, which would be unusual to say the least.

**Comment by Byron** [comment]
Oh, and as a follow-up test, can you disable the `process = git-lfs filter-process` line? What happens then?

**Comment by Byron** [comment]
Actually never mind any of that - after having applied a couple of fixes and improvements, I can now reproduce the issue.

**Comment by gl-yziquel** [comment]
I have no problem using git lfs as I did download quite a bit from huggingface.

But I did not understand what you asked me to do.

"Glad" that you managed to reproduce the issue.

Please keep me informed.

**Comment by Byron** [comment]
I will!

Meanwhile, may I ask why you use `gix` in the first place? A wild guess would be that it's faster, but maybe it's something else even?

If it is faster, could you share a percentage or multiplier?

**Comment by gl-yziquel** [comment]
Uhhh... because I'm a geek ?

I like using new tools. I like rust. I experienced with your original python code for git as I aim to write a python tool to make automated small changes on my local personal git repos. Noticed you moved on to gitoxide. Tried it out for fun. Been using it since the middle of the week. I like it.

**Comment by Byron** [comment]
Hehe, that's fair enough :)!

Maybe it's just the right tool for some aspects of a workflow, as long as there is no expectation that it can drive an entire workflow - after all, it's just a development tool to test the `gix` library in the real world.

I have results now, by the way, as it's clear that neither `git` nor `git-lfs` considers the new repository valid. Unfortunately, `git-lfs` manages to output its error message on `stdout`, which is reserved for 'protocol' talk, hence the message about the handshake failing.

Now I just have to figure out what's wrong with the repository in such a way that `gitoxide` can open it, but `git` can't (at least apparently).

**Comment by gl-yziquel** [comment]
> Maybe it's just the right tool for some aspects of a workflow, as long as there is no expectation that it can drive an entire workflow - after all, it's just a development tool to test the `gix` library in the real world.

I like living dangerously. Sometimes.

> I have results now, by the way, as it's clear that neither `git` nor `git-lfs` considers the new repository valid. Unfortunately, `git-lfs` manages to output its error message on `stdout`, which is reserved for 'protocol' talk, hence the message about the handshake failing.

I somehow guessed this repo was kind of an odd ball.

**Comment by Byron** [comment]
Actually it's fixed now. The problem for you was that the filter process was spawned in the CWD, which didn't have a repository. Now it's told where to look with environment variables, which makes it work.

Just have to wrap it up now and then you can use the version from `main` with the fix.

**Comment by Byron** [comment]
Please let me know if `main` works for you now. I am pre-emptively closing the issue, but hope you will let me know if something is still wrong here anyway, or reopen it if needed.

Thanks.

**Comment by gl-yziquel** [comment]
I tried to download the same repo with a recompiled gix.

It worked.
