### ISSUE TITLE
Inconsistency in gix clone with repo url with a dot.

### ISSUE THREAD

**Issue by gl-yziquel** [Byron/gitoxide#1177]
### Current behavior 😯

I have issued the following command:

```console
gix clone https://github.com/cidrblock/drawthe.net
```

Weirdly enough, the cloned repo on my filesystem is named `drawthe` and not `drawthe.net`.

I believe this is an inconsistency that should be fixed. Removing the `.git` suffix is ok. Removing the `.net` suffix, not quite so.

### Expected behavior 🤔

It should keep the `.net` suffix.

### Git behavior

It keeps the `.net` suffix.

### Steps to reproduce 🕹

```console
gix clone https://github.com/cidrblock/drawthe.net
```

**Comment by Byron** [comment]
Thanks a lot for letting me know!

A fix will be available with the next release, probably by the end of the year.
