### ISSUE TITLE
Updating packed-refs fails on Windows if `mmap`-ed (i.e. file size is over 32KiB)

### ISSUE THREAD

**Issue by yuja** [Byron/gitoxide#1183]
### Current behavior 😯

`FileTransactionCommit` of `packed-refs.lock` fails with Os error 5 `PermissionDenied` "Access is denied."

### Expected behavior 🤔

Packed refs can be updated by using gix `Repository` API.

### Steps to reproduce 🕹

The following code creates lots of refs, runs `git pack-refs`, and deletes one by using `repo.find_reference()`/`.delete()`.
https://gist.github.com/yuja/b922bc0881c0912dad9c1a6a78f0703f

It works normally on Linux, but fails on Windows.

I think the problem is that the `mmap`-ed file prevented the rename of `packed-refs.lock` -> `packed-refs`. Rust's stdlib appears to set `FILE_SHARE_DELETE` flag to avoid this kind of problems on Windows, but I have no idea if there's a similar escape hatch for Windows mmap API.

More details can be found in the following issue.
https://github.com/martinvonz/jj/issues/2697

(@jennings helped us debug the issue, thanks.)

**Comment by Byron** [comment]
Thanks for reporting! 

A test for this is definitely missing (as in: delete while packed refs is memmapped), and I will rectify this along with a 'fix' (which probably has to be to simply not mmap on Windows).

**Comment by yuja** [comment]
> a 'fix' (which probably has to be to simply not mmap on Windows).

Yeah. There would be no reasonable workaround if mmaped file can't be deleted. External git process should be able to update packed-refs while it is mmapped by gix.

**Comment by Byron** [comment]
I have just released [a patch for `gix-ref`](https://crates.io/crates/gix-ref/0.39.1) and you are welcome to try it. In my CI testing, the patch did resolve the issue described here that was reproduced beforehand.

**Comment by yuja** [comment]
Thanks for the quick fix!

@jennings, can you test this with your repo?
https://github.com/yuja/jj/tree/push-vroloysozmyx (or update jj to the current main and run `cargo update gix-ref`)

**Comment by Byron** [comment]
Please keep me posted on how it goes (despite this issue being auto-closed by the PR). I am pretty optimistic that it works now and hope it will work for you, too.

**Comment by jennings** [comment]
The error no longer occurs for me after upgrading to gix-ref 0.39.1. Thanks @Byron and @yuja for such a quick turnaround!
