### ISSUE TITLE
some dependencies are yanked

### ISSUE THREAD

**Issue by ognevnydemon** [Byron/gitoxide#1204]
### Summary 💡

I recieve this when building `gitoxide 0.32.0` using `cargo build --release --locked --no-default-features --features max-pure`
```
warning: package `ahash v0.8.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `tracing v0.1.39` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```

### Motivation 🔦

it's just cool to update yanked deps ;)

**Comment by Byron** [comment]
Thanks a lot for making me aware.

There wasn't a test for this nor does it show up during local development, but it's now easier to find by hand.
Please note that I decided not to make yanked crates fail CI as it would most certainly cause failures at arbitrary times for something outside of my control.
Thus, be prepared for creating more of these issues as the needed arises, but maybe the probably is now lower thanks to `just find-yanked` that would manually find yanked crates at least.
