### ISSUE TITLE
gix-index failing to build on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [Byron/gitoxide#1213]
### Current behavior 😯

Hi,

It's me again ...
Any hints about this one, https://github.com/starship/starship/issues/5659 ?

Or, maybe it's time for me to dig into `libc` again.

**Comment by Byron** [comment]
I think this [is already fixed](https://github.com/starship/starship/issues/5659#issuecomment-1871847576) - closing for that reason, but feel free to reopen if that turns out not to be the case after all.

**Comment by 0323pin** [comment]
I'll give the PR branch a go when I find the time, thanks.

**Comment by 0323pin** [comment]
@Byron sorry for the noise, I should have looked at the version in the `starship` dependency tree and crosschecked. It was already fixed, as you pointed and building `starship` with the latest `gix-index` works just fine.
