### ISSUE TITLE
Provide usage examples for the `Find` trait

### ISSUE THREAD

**Issue by Shnatsel** [Byron/gitoxide#1216]
### Summary 💡

I am upgrading the `rustsec` crate from `gix` 0.55.x to 0.56, and I am having trouble wrapping my head around some of the API changes.

I have this snippet in 0.55.x:

```rust
        let index = gix::index::State::from_tree(&root_tree, |oid, buf| {
            repo.objects.find_tree_iter(oid, buf).ok()
        })
```

In 0.56 the closure has been replaced with the [`Find` trait](https://docs.rs/gix/0.56.0/gix/prelude/trait.Find.html) requirement, so my code no longer compiles. Neither the `from_tree` function nor the `Find` trait provide any usage examples. 

It would be great if the documentation provided an example of how to use this API.

**Comment by Byron** [comment]
Sorry for the trouble, this was quite a big but necessary change. 

The snippet should work like this:

```Rust
        let index = gix::index::State::from_tree(&root_tree, &repo.objects)
```

> It would be great if the documentation provided an example of how to use this API.

It's definitely on the `TODO` list, but it will a while until plumbing crates get examples. Hence I recommend to CC me on a PR or ask here with snippets for help in the meantime.

**Comment by Shnatsel** [comment]
That's understandable. Your solution compiles, I didn't get to test it yet due to other compilation errors.

I am struggling to understand two more places where the `Find` trait is used in our code:

https://github.com/rustsec/rustsec/blob/f79b59b45dc7b04f584c524b4c482dffce7f158a/rustsec/src/repository/git/commit.rs#L156-L162

and 

https://github.com/rustsec/rustsec/blob/f79b59b45dc7b04f584c524b4c482dffce7f158a/rustsec/src/repository/git/modification_time.rs#L119-L124

Could you perhaps help with those as well?

**Comment by Byron** [comment]
I have answered the questions by applying the changes in the linked PR - it needs some work though to go through and I am on it.
