### ISSUE TITLE
Rewrite tracker panics on BlobExecutable

### ISSUE THREAD

**Issue by iceghost** [Byron/gitoxide#1224]
When I was trying to generate the diff for this commit: https://github.com/LukeMathWalker/zero-to-production/commit/656ee46c0933b2baac2e81cdb4d25ca903bbc7bd, `gix-diff` panicked:

```
thread 'main' panicked at /home/khang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-diff-0.39.1/src/rewrites/tracker.rs:471:9:
assertion `left == right` failed: symlinks are matched exactly, and trees aren't used here
  left: BlobExecutable
 right: Blob
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/Byron/gitoxide/blob/62e1072b28b965cfaa4d25831d9b8a12bb7c67c2/gix-diff/src/rewrites/tracker.rs#L468-L476

Maybe a variant is missing there?

**Comment by Byron** [comment]
Thanks for reporting!

The intention was to check for blobs, which can also be executable, even though the expectation ended up only allowing blobs, not executables.

This is now fixed. Fortunately this was only an issue in debug builds.

Or could it be that this happens in one of your release builds? If so, could you remind me which manifest key is needed to enable debug assertions in release builds?

**Comment by iceghost** [comment]
@Byron Thanks for the fast fix! It was indeed on my Debug build, so no problem there.
