### ISSUE TITLE
A lot of unrelated tags, like gix-testtools, make it difficult to discover new gitoxide versions

### ISSUE THREAD

**Issue by yurivict** [Byron/gitoxide#1270]
### Expected behavior 🤔

It's not clear from looking at tags what is the latest gitoxide version is.

Could you please consider to limit tags to gitoxide-related ones?

Thanks,
Yuri (maintainer of the FreeBSD port devel/gitoxide).

**Comment by Byron** [comment]
It's part of the release process to create a tag for each crate, and I see why that would be overwhelming given the amount of crates and release.
However, I am afraid I don't have a better way, while also thinking that outside of the GitHub user interface this is quite manageable.

To get the latest version of the `gix` and `ein` binaries, `git tag -l  --sort=-v:refname  | head -1` does the trick.

Somehow I feel it's something you already now though, so any details regarding your workflow would be appreciated, maybe there is a solution for the issues you encounter that I can help with.

Closing, as I don't think changing the `cargo smart-release` workflow and the tags it creates is feasible right now.
