### ISSUE TITLE
Gix doesn't call the credentials helper properly

### ISSUE THREAD

**Issue by jalil-salame** [Byron/gitoxide#1284]
### Current behavior 😯

Setting `git config credential.helper` on a repository that needs a password works with `git` but fails with `gix`.

You can see the error by setting `git config credential.helper '!echo "$@" >&2'`.

It would also be nice if it printed the `remote` message that git prints too on failure.

I am using the `nixpkgs-unstable` version of `gitoxide` (v0.33.0).

### Expected behavior 🤔

Setting `git config credential.helper '!echo "$@" >&2'` and running `gix fetch` should print `get` once. It instead prints `get get`.

### Git behavior

Setting `git config credential.helper '!echo "$@" >&2'` and running `git fetch` prints `get` once. 

### Steps to reproduce 🕹

1. Clone a private repo (i.e. with ssh).
2. Change the remote to one that requires authentication (i.e. https).
3. Run `git config credential.helper '!echo "$@" >&2'` (you can also set this globally and see `gix clone` fail).
4. Run `gix fetch` and see it print `get get`:

    ```console
    $ gix fetch
    get get
    Cannot run askpass program: "" with error: No such file or directory (os error 2)
    Username for https://github.com: jalil-salame
    Cannot run askpass program: "" with error: No such file or directory (os error 2)
    Password for https://jalil-salame@github.com:
    erase erase(authenticated) 1 steps [   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===   ===]
    Error: Credentials provided for "https://github.com/jalil-salame/gix-private-test.git" were not accepted by the remote

    Caused by:
        Received HTTP status 401
    ```

5. Run `git fetch`:

    ```console
    $ git fetch

    get
    Username for 'https://github.com': jalil-salame
    Password for 'https://jalil-salame@github.com':

    erase
    remote: Support for password authentication was removed on August 13, 2021.
    remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
    fatal: Authentication failed for 'https://github.com/jalil-salame/gix-private-test.git/'
    ```

**Comment by jalil-salame** [comment]
Actually, this seems to be cause by the `"$@"` being expanded and `get` being provided, if I remove the `"$@"` (`git config credential.helper '!echo >&2'`), both `git` and `gix` work the same way.

It is still desirable to match `git`'s behavior as [`pass-git-helper`](https://github.com/languitar/pass-git-helper) suggests this.

The way git handles this is weird: `!echo $@ $@` prints `get` thrice in `gix`, but only once in `git`.

**Comment by jalil-salame** [comment]
Without looking at the git credential's implementation. My guess is that git just adds a `get` at the end of the command (i.e. `echo $@ $@` -> `echo $@ $@ get`) while `gix` both adds a `get` at the end and calls it with `get` (i.e. `echo $@ $@` -> `sh -c 'echo $@ $@ get' -- get`). Which would explain the difference in behavior.

Another clue is `!echo $@ >&2 exit 1` will print `get` then fail with too many arguments for exit when using `gix` and it prints nothing before failing the same way when using `git`.

**Comment by Byron** [comment]
Thanks so much for reporting - I could reproduce the issue.

It boils down to the following: When detecting that a script should be executed, it applies a 'trick' to pass arguments. With that, it ends up invoking `/bin/sh -c 'echo "$@" >&2 "$@"' -- store` even though it should invoke `/bin/sh -c 'echo "$@" >&2' $@ -- store`.

Somehow, the `$@` which is part of the 'trick' ends up as part of the script itself, not as a separate argument.

I'd expect to have a fix for that soon.

**Comment by jalil-salame** [comment]
> I have made a symptomatic fix in #1286 that you could try, even though I think that there is more going on here.
> From what I can tell, running credential helpers works fine, and it's the doubling of arguments in this specific case has nothing to do with its correct functioning.
> 
> Thus, I don't know what else I can do as I don't actually understand the problem. Admittedly, I also don't understand how Git manages to not double the arguments [given its code](https://github.com/git/git/blob/master/run-command.c#L289-L295) - maybe it doesn't run into this code at all which is also the reason that they suggest to add `$@` in the end of the script even though that's not needed with the way `gitoxide` is currently functioning.
> 
> After having written this, I do believe I understand the issue, which is to get credential helpers to work that use `$@` like described in [pass-git-helper](https://github.com/languitar/pass-git-helper), and I do think that's the case now.

I feel like git has legacy behavior which the helpers work around by using $@. I'll take a look at the code and see what I can figure out.

**Comment by Byron** [comment]
I have merged the PR and you could try it out for a spin on `main` if you want. 

The following should do the trick.

```
cargo build --bin gix --no-default-features --features max-pure
./target/debug/gix …
```

Your particular usecase is handled now, and if it's not working you can get more information using `gix --trace -v …`.

Thanks for helping with validating the change 🙏.

**Comment by jalil-salame** [comment]
So this fixes the common case `credential.helper '!pass-git-helper "$@"'`, which is all I (and hopefully everyone) will need, but it still has differences with `git`:

```console
$ git config credential.helper '!echo "$@" "$@" >&2'
$ gix-v0.33.0 fetch
get get get
...
^C
$ gix-main fetch
get get
...
^C
$ git fetch
get
...
^C
```

Why git does that? I can't tell. As far as I understand from the linked git code it should behave like `gix-v0.33.0` and print `get get get`.

Do you have an issue to track known differences to `git`? This feels like it should not impact anyone, but it should be documented somewhere.

**Comment by jalil-salame** [comment]
Another example of `gix-main` and `git` handling things differently:

```console
$ git config credential.helper '!echo "$@" "$@" >&2 && exit 1'
$ gix-v0.33.0 fetch
get get
--: line 1: exit: too many arguments
Cannot run askpass program: "" with error: No such file or directory (os error 2)

$ gix-main fetch
get get
Cannot run askpass program: "" with error: No such file or directory (os error 2)

$ git fetch

echo "$@" "$@" >&2 && exit 1 get: line 1: exit: too many arguments
Password for 'https://jalil-salame@github.com':
```

This suggests that the commands are:
- `gix-v0.33.0`: `sh -c 'echo "$@" "$@" >&2 && exit 1 get' -- get`.

**Comment by Byron** [comment]
Thanks for this gem! 

When using `GIT_TRACE=1` I see `trace: run_command: 'echo "$@" "$@" >&2 store'` and `'echo "$@" "$@" >&2 && exit 1 store'` respectively. This explains why it prints a single `store` - the script has no arguments, and all it does is to add `store` [to the end of the script itself](https://github.com/git/git/blob/2996f11c1d11ab68823f0939b6469dedc2b9ab90/credential.c#L354).

`gitoxide` now says this, which I believe is consistent and provides the expected results.
```
 07:27:54 tracing DEBUG    │     ┝━ gix_protocol::handshake() [ 524ms | 70.96% ] service: UploadPack | extra_parameters: []
 07:27:54 tracing DEBUG    │     │  ┝━ 🐛 [debug]: launching credential helper | cmd: "git" "credential-osxkeychain" "get"
 07:27:54 tracing DEBUG    │     │  ┝━ 🐛 [debug]: launching credential helper | cmd: "git" "credential-osxkeychain" "store"
 07:27:54 tracing DEBUG    │     │  ┝━ 🐛 [debug]: Will not add '$@' to '"echo \"$@\" \"$@\" >&2 && exit 1"' as it seems to contain it already
 07:27:54 tracing DEBUG    │     │  ┝━ 🐛 [debug]: launching credential helper | cmd: "/bin/sh" "-c" "echo \"$@\" \"$@\" >&2 && exit 1" "--" "store"
 07:27:54 tracing DEBUG    │     │  ┝━ 🐛 [debug]: Will not add '$@' to '"echo \"$@\" \"$@\" >&2 && exit 1"' as it seems to contain it already
 07:27:54 tracing DEBUG    │     │  ┕━ 🐛 [debug]: launching credential helper | cmd: "/bin/sh" "-c" "echo \"$@\" \"$@\" >&2 && exit 1" "--" "store"
```

It always runs the helper in a shell, which is why that usually works. I do not know where the `$@` suggestion in `pass-git-helper` is coming from though, as it should not be required at all even for Git.

From all I can tell, `gitoxide` is consistent here as it uses the same engine for invoking commands as it always does, which should support typical Git use-cases, while being more open overall.

In any case, I think this concludes this interesting exploration into the depth of Git interactions with credential helper, and documentation some of these have :).

**Comment by nrdxp** [comment]
Is this fix in the latest release in crates.io? I can't seem to get https credentials to work at all, however ssh creds work fine. 

If I understood the docs correctly it should search for creds automatically but I've tried to do it explicitly as well:
```rust
        let mut client_req = context.remote.connect(Direction::Push)?;
        let url = context.remote.url(Direction::Push);
        if let Some(url) = url {
            let creds = client_req.configured_credentials(url.clone());
            if let Ok(creds) = creds {
                client_req = client_req.with_credentials(creds);
            }
        };
```

However ssh works without any of this explicit credential setting. I always just get an IO error with https, but ssh works fine

**Comment by Byron** [comment]
The only reason this might happen is if it doesn't know the configured credential helpers - some come with the Git installation, and are in a special configuration that only the `git` binary knows.

To enable it, you'd want to set `git_binary = true` similar to what [the `gix` binary does](https://github.com/Byron/gitoxide/blob/7249291016253647c920852fb37eb9e29d615775/src/plumbing/main.rs#L98-L99).

That's another way to double-check what the problem might be - using the `gix` command-line tool to do what you are trying to do.

Further, the following should probably be `Direction::Fetch` as pushing isn't implemented yet.

```Rust
let mut client_req = context.remote.connect(Direction::Push)?;
```

I hope that helps.
