### ISSUE TITLE
Oxidize comtrya

### ISSUE THREAD

**Issue by yonas** [Byron/gitoxide#1320]
### Summary 💡

gitoxide is missing a few features mentioned in [#347](https://github.com/comtrya/comtrya/issues/347#issuecomment-2000445359):

```
It can't perform the equivilent of a git pull, which is a fetch, merge, and potentially rebase.

IIRC, merge and rebase aren't implemented and it's been that way for a while.
```

**Comment by Byron** [comment]
Thanks for letting me know.

It definitely will be a while until rebase is implemented, but on the bright side, I am working on `git reset/checkout` functionality already. Merge is certainly further out as well though.

To stay conformant with my oxidization workflow and ticket style, I created #1321 to supersede this one, along with all information provided here.
