### ISSUE TITLE
Writing special package to git-packetline Writer

### ISSUE THREAD

**Issue by mellowagain** [Byron/gitoxide#137]
I've got a quick question regarding git-packetline that you wrote. I've wondered how one would write special packets such as flush (0000), delimiter (0001) or response end (0002) to it. 

I've tried using `write` in binary mode but that prefixes it with the length as if it was a normal packet line. I've also tried accessing the inner writer to write to it manually (I used to do that in the previous version 0.5.0 but now that the `inner` is private I can no longer do that)

**Comment by Byron** [comment]
Indeed, plumbing crates APIs are quite unstable still, and it's super valuable to learn if it's still working or not.

Fortunately your case is still supported, as you can write message like so:

https://github.com/Byron/gitoxide/blob/3d2456e11709f0461b37c6df55ecc3861ca4cab5/git-transport/src/client/async_io/request.rs#L59-L83

Hope that helps.
