### ISSUE TITLE
Backport outside traversal fix to v0.62.x

### ISSUE THREAD

**Issue by rillian** [Byron/gitoxide#1377]
### Current behavior 😯

Trying to address audit reports about [GHSA-7w47-3wg8-547c](https://github.com/advisories/GHSA-7w47-3wg8-547c) I ran into a [weird build error](https://github.com/rustsec/rustsec/pull/1194#issuecomment-2127849340) updating `rustsec` to `gix 0.63.0` which I don't understand how to resolve.

Would you consider backporting the fix to a crate tree rooted in `gix 0.62.x` so we can just semver-bump our Cargo.lock in the meantime?

### Steps to reproduce 🕹

1. git clone https://github.com/rustsec/rustsec
2. cd rustsec/rustsec
3. Edit Cargo.toml to require gix 0.63
4. cargo check

**Comment by Byron** [comment]
I think the problem is that `tame-index` didn't update yet. I will see to submitting a PR for that in a bit.
I think we can make this work, so a backport won't be necessary.

**Comment by rillian** [comment]
Yes, that seems to have resolved the build issue. Thanks for following up!
