### ISSUE TITLE
`gix-mailmap` parser treats mappings with old but not new names as an error

### ISSUE THREAD

**Issue by emilazy** [Byron/gitoxide#1416]
### Current behavior 😯

`<b> test <a>` is silently discarded, unlike `<b> <a>` and `test2 <b> test1 <a>`

### Expected behavior 🤔

Old names, new names, and new emails should be treated uniformly; any combination that includes an old email address should parse and function.

### Git behavior

Git treats this entry as valid and maps signatures accordingly:

```
emily@yuyuko ~/gix-mailmap-bug> git init
Initialized empty Git repository in /Users/emily/gix-mailmap-bug/.git/
emily@yuyuko ~/gix-mailmap-bug (main)> echo '<b> test <a>' >.mailmap
emily@yuyuko ~/gix-mailmap-bug (main)> git check-mailmap 'test <a>'
test <b>
```

### Steps to reproduce 🕹

```
emily@yuyuko ~/gix-mailmap-bug (main)> cat src/main.rs
use gix::actor::SignatureRef;
use gix::mailmap;

fn main() {
    let mailmap = mailmap::Snapshot::from_bytes(b"<b> test <a>");
    let signature = SignatureRef {
        name: "test".into(),
        email: "a".into(),
        time: Default::default(),
    };
    dbg!(mailmap.entries(), signature, mailmap.resolve(signature));
}
emily@yuyuko ~/gix-mailmap-bug (main)> cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/gix-mailmap-bug`
[src/main.rs:11:5] mailmap.entries() = []
[src/main.rs:11:5] signature = SignatureRef {
    name: "test",
    email: "a",
    time: Time {
        seconds: 0,
        offset: 0,
        sign: Plus,
    },
}
[src/main.rs:11:5] mailmap.resolve(signature) = Signature {
    name: "test",
    email: "a",
    time: Time {
        seconds: 0,
        offset: 0,
        sign: Plus,
    },
}
```

**Comment by Byron** [comment]
Thanks a lot for reporting and for making it so easy to reproduce!

I think that's the one valid case that I somehow missed.

Once the linked PR is merged, I will create a patch-release with the fix, which should be picked up by recent `gix` crates.

**Comment by emilazy** [comment]
Ah, you beat me to it! I just opened this to have something to track the issue as I worked on a fix myself. Thanks for the extremely quick response!

**Comment by Byron** [comment]
Then I invite you to review my PR - maybe there is something that you had in mind that could be added there as well.
