### ISSUE TITLE
`gix_mailmap::Snapshot` does not implement `Debug` or `Eq`

### ISSUE THREAD

**Issue by emilazy** [Byron/gitoxide#1424]
### Summary 💡

It would be nice to be able to print and compare `.mailmap` snapshots for equality. Ideally the semantics would be the same as with `.entries()`, but without allocating a new `Vec`.

### Motivation 🔦

I would like to include this type in types that `#[derive(Debug, PartialEq, Eq)]` for https://github.com/martinvonz/jj/pull/3951, and it just seems like generally‐useful functionality to have.

**Comment by Byron** [comment]
Thanks for letting me know!

Is this something you'd like to submit a PR for? If not (or it's more complicated), I am happy to pitch in.

**Comment by emilazy** [comment]
I can try to find the time to take a look once I’ve popped enough other tasks off the stack. But maybe just `#[derive]` would work here? It might not produce the prettiest output for `Debug`, though.

**Comment by Byron** [comment]
Alright, a PR is up, and the debug print should be fine (it's just a Vec internally).

**Comment by Byron** [comment]
And the fix is available here: https://github.com/Byron/gitoxide/releases/tag/gix-mailmap-v0.23.3
