### ISSUE TITLE
gix-config set configuration values

### ISSUE THREAD

**Issue by tbugfinder** [Byron/gitoxide#1445]
### Summary 💡

Currently gix-config only reads the config settings.
It doesn't write configuration updates - as far as I could figure out.

```
$ /tmp/gix config core.filemode false

# From '.git/config' (GitInstallation)
[core]
repositoryformatversion=0
filemode=true
bare=false
logallrefupdates=true
symlinks=true
ignorecase=false
precomposeunicode=false


# From './.git/config' (Local)
[core]
repositoryformatversion=0
filemode=true
bare=false
logallrefupdates=true
symlinks=true
ignorecase=false
precomposeunicode=false

```

### Motivation 🔦

use gix as a drop-in replacement for git :-D

**Comment by Byron** [comment]
Thanks for your interest!

As `gix` is a development tool, as such its purpose is to allow testing new algorithms on real repositories. `gix config` with write capabilities for the sake of replicating `git` isn't part of that purpose.

Of course, anybody is welcome to contribute it if they think they can improve on what's provided by `git`, which might well be possible as in theory, `gix-config` should be less destructive. But thus far I don't know of any reason for not using `git config` to edit the configuration. 

Thanks for your understanding.
