### ISSUE TITLE
Something went wrong... & Merge conflict after working on another device

### ISSUE THREAD

**Issue by andrebaerlocher** [Byron/gitoxide#1452]
### Current behavior 😯

I had the following problems the last few times I tried working on a repo on a different device:
<img width="608" alt="image" src="https://github.com/user-attachments/assets/9ff62ff3-500f-4ec9-b221-a3b7d6166671">

1. On device 1 I pushed all my commits of 3 branches (visuelles, komponenten, daten), so every branch was clean
2. On device 2 all commits were present, I worked on the 3 branches (offline, though)
3. When I tried to commit the changes from device 2 I got an error in the Workspace "Something went wrong...", in the console:
```
[Error] ipc->list_virtual_branches: {"projectId":"9dae42be-4456-4b05-9826-0e4a54aed589"} (2)
Error: Merge conflict between base and "daten"
Object

code: "errors.unknown"

message: "Merge conflict between base and \"daten\""

Object Prototype
	(anonymous function) (ipc.zofQMm0f.js:1:2373)
[Warning] Error: Merge conflict between base and "daten" (Button.D8XivPza.js, line 3)
```

This is the second time this happened, at the first I thought I buggered up.

Also, there were suddenly more branches, now there are 4 (instead of 3), one was duplicated, apparently the one with the merge conflict.
<img width="767" alt="image" src="https://github.com/user-attachments/assets/5c633ecd-4b2e-4b1a-8b4a-552d3a3da37c">
<img width="767" alt="image" src="https://github.com/user-attachments/assets/c417e5d7-a8ff-4ec9-b148-ada4d49ff0b3">

I can't apply any of the branches.

### Expected behavior 🤔

- No error
- No merge conflict (or the possibility to resolve the merge conflict)

### Steps to reproduce 🕹

1. Commit from device 1
2. Work from device 2 (not sure if you have to be offline or not)

**Comment by Byron** [comment]
I think you want to re-post this issue over at [GitButler](https://github.com/gitbutlerapp/gitbutler/issues) :).
