### ISSUE TITLE
Why do you repeat star the `gitoxide` 😂

### ISSUE THREAD

**Issue by iamazy** [Byron/gitoxide#16]

**Comment by Byron** [comment]
😂 I didn't know people can actually see this!
It's my way of seeing how many stars there are and I like the count going up :D.

**Comment by Byron** [comment]
Can you fill me in on how this is visible?
In any case, closing this issue as Q&A. Please feel free to respond in the closed issue.

**Comment by iamazy** [comment]
Just look in github index page ([github](https://github.com)). 
![image](https://user-images.githubusercontent.com/16559960/90495016-b0fd4400-e176-11ea-9037-53ecdbf12cdf.png)
I think everyone can see this as long as he/she has followed you

**Comment by Byron** [comment]
Hehe, ok, so it's kind of spammy for people :D.

Thanks for letting me know! I will just click the stargazers page in future :)!

**Comment by iamazy** [comment]
I'm Ok about this action, Don't be influenced by my question😂
