### ISSUE TITLE
Shallow clone support 

### ISSUE THREAD

**Issue by Ludea** [Byron/gitoxide#18]
I see this commit https://github.com/Byron/gitoxide/commit/dc7908f1546239ade71f4147a389a001769311f5
You don't plan to support shallow clones ?

**Comment by Byron** [comment]
Good catch! I removed that line as it seemed to imply shallow cloning has its own portion of the protocol. However, it's only a different way to do fetches and those implementing the protocol, e.g. the Repository, will be able to support shallow clones.

I made that more explicit in the README now, and am thus closing this ticket.

**Comment by Ludea** [comment]
Thanks for the clarification :)
