### ISSUE TITLE
Is there a crate I can use programatically?

### ISSUE THREAD

**Issue by Milo123459** [Byron/gitoxide#182]
I want to use all of the Gitoxide CLI commands without installing the CLI (weird, I know!) I just want to access the APIs of how Gitoxide works, so for example a crate so I can do `gitoxide::pull(..)` etc

**Comment by Byron** [comment]
Thanks for your interest. What you are looking for is the [`gitoxide-core`](https://docs.rs/gitoxide-core/0.9.0/gitoxide_core/), which is what powers the CLI. It allows to control input and output as well, so it can be used with graphical user interfaces as well.

You probably want to build the latest docs from source for now to get an overview, as it currently doesn't build on docs.rs.
