### ISSUE TITLE
`cargo-smart-release`: not using bumped version for some reason

### ISSUE THREAD

**Issue by dyc3** [Byron/gitoxide#186]
Context: I've made some changes to one crate, `steamguard-cli`, but the other crate hasn't changed `steamguard`. It looks like the version for `steamguard` dictates the version of `steamguard-cli`?

Output
```
[WARN ] Consider running with --update-crates-index to assure bumping on demand uses the latest information
[WARN ] Using 'steamguard-cli' as crate name as no one was provided. Specify one if this isn't correct
[INFO ] steamguard v0.4.0  - skipped release as it didn't change
[INFO ] Using current version 0.4.0 instead of bumped one 0.4.1.
[INFO ] Congratulations for the new release of 'steamguard-cli' 🎉
[INFO ] Will prepare release of steamguard-cli v0.4.0
[INFO ] Pending 'steamguard-cli' manifest version update: "0.4.0"
```

**Comment by dyc3** [comment]
Running with `--update-crates-index` appears to fix it. Seems a little quirky imo.

**Comment by Byron** [comment]
I agree. I run into this myself but am also happy it doesn’t add latency every time you call.

Maybe some more tuning is possible, in case you have suggestions.
