### ISSUE TITLE
Windows builds is broken

### ISSUE THREAD

**Issue by MCOfficer** [Byron/gitoxide#19]
Edit: oops, opened this without content. hang on a second.

This is kind of a tracking issue for the currently broken windows build, as mentioned in the latest release.

I opened this because i needed a space to leave my findings, specifically this issue: <https://github.com/actions/virtual-environments/issues/1143>. I never worked with cross before, but perhaps it's an option to run this workflow on a linux runner?

**Comment by Byron** [comment]
Thanks for taking a look.
Actually there is, and maybe it’s as easy as that.

I wonder why it breaks all of the sudden, maybe GitHub changed their configuration to prevent people from using windows hosts to run linux in docker. I for one wasn’t aware cross does that 😄

**Comment by Byron** [comment]
Looks like that doesn't work: https://github.com/Byron/gitoxide/runs/1105438098?check_suite_focus=true#step:8:266 , i.e. it does need windows for the final link step.

**Comment by MCOfficer** [comment]
But that is the msvc target. From my understanding, only the gnu target runs a linux container, the msvc target can remain as-is.

**Comment by MCOfficer** [comment]
Seems like you fixed it?

**Comment by Byron** [comment]
Great! Looks like the installation was broken for everyone, and that was just fixed.

I am glad this issue wasn’t windows specific.
