### ISSUE TITLE
git-config towards 1.0

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#191]
A list of ideas for features that come up when using `git-config::file::GitConfig`

* `Boolean` can act as `bool` or be converted to one, maybe using deref
* `Integer` derefs to integer
* Something like `try_value() -> Result<Option<T>, E>` as currently I am ignoring all errors as it's too cumbersome to check if the conversion failed which probably should be an actual 
* could there be a more convenient API than [this](https://github.com/Byron/gitoxide/blob/d0a956fdb5a822dbd116792bfbe70d1532a95ec9/git-repository/src/repository.rs#L74-L76).

### Missing features

* [ ] cascading config files
* [ ] know which config files to cascade
* [ ] actual `PathBuf` instead of just a string
* [ ] comfortable API for accessing values
* [ ] include directive

### Related Discussions

- https://github.com/Byron/gitoxide/discussions/166
- https://github.com/Byron/gitoxide/discussions/147
- https://github.com/Byron/gitoxide/discussions/54

**Comment by edward-shen** [comment]
What would you suggest for a concrete implementation then? A separate type `ParserValue` and a serde friendly enum? Or just enhancements to the existing `Value` (e.g. `as_*`) and `to_owed`?

Ironically enough, serde compatibility was always a goal from the beginning but never achieved (yet)
