### ISSUE TITLE
[cargo smart-release] Automatically bump major versions of pre-release dependents if dependee is bumped

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#192]
Solve this:

* `A` and `B` are workspace crates
* `C` is a workspace-external crate
* `B` is re-released with breaking changes

```                                                                 
                              1) Start════════════════════════════════════╗                         
                              ║                                           ║                         
                              ║                                           ║                         
                              ║                                           ║                         
                              ║      ┌───┐      ┌───┐                     ║                         
                              ║      │B 1│◀─────│A 1│◀────┐               ║                         
                              ║      └───┘      └───┘     │               ║                         
                              ║                           │     ┌───┐     ║                         
                              ║                           ├─────│c 1│     ║                         
                              ║                           │     └───┘     ║                         
                              ║                 ┌───┐     │               ║                         
                              ║                 │B 1│◀────┘               ║                         
                              ║                 └───┘                     ║                         
                              ║                                           ║                         
                              ║                                           ║                         
                              ║                                           ║                         
                              ╚═══════════════════════════════════════════╝                         
                                                    │                                               
                          ┌────────────Problem──────┴────────────Solution────┐                      
                          │                                                  │                      
                          ▼                                                  ▼                      
    2) Minor bump A, Major bump B C 1 gets latest      2) Major bump A, Major bump B C 1 does not ═╗
    ║                                           ║      get latest                                  ║
    ║                                           ║      ║      ┌───┐      ┌───┐                     ║
    ║                                           ║      ║      │B 2│◀─────│A 2│                     ║
    ║      ┌───┐     ┌─────┐                    ║      ║      └───┘      └───┘                     ║
    ║      │B 2│◀────│A 1.1│◀───┐               ║      ║      ┌───┐      ┌───┐                     ║
    ║      └───┘     └─────┘    │               ║      ║      │B 1│◀─────│A 1│◀────┐               ║
    ║                           │     ┌───┐     ║      ║      └───┘      └───┘     │               ║
    ║                           ├─────│c 1│     ║      ║                           │     ┌───┐     ║
    ║                           │     └───┘     ║      ║                           ├─────│c 1│     ║
    ║                 ┌───┐     │               ║      ║                           │     └───┘     ║
    ║                 │B 1│◀────┘               ║      ║                 ┌───┐     │               ║
    ║                 └───┘                     ║      ║                 │B 1│◀────┘               ║
    ║                                           ║      ║                 └───┘                     ║
    ║                                           ║      ║                                           ║
    ║                                           ║      ║                                           ║
    ╚═══════════════════════════════════════════╝      ╚═══════════════════════════════════════════╝
```

In 2), the problem is that two incompatible versions of `B` are used and that such an upgrade happens automatically unless the user has pinned dependencies. This, however, also prevents patch releases which they definitely want, and it's not helping with pre-release versions either.

In 3) as proposed solution, all crates that use the bumped one (within the workspace) receive the same major version bump to prevent them from being upgraded to automatically by their users.

**Comment by Byron** [comment]
@epage The above is an issue I ran into today and many times before that. What do you think about the proposed solution? Maybe it's something that `cargo release` already solves? I am curios to pick your brain about this. Thank you :).

**Comment by epage** [comment]
I feel like I'm not quite getting it from the image.  What all is in a workspace vs not?   Why, when bumping B does C not get updated to point to B2?

If this is the situation I think it is, where A includes B in its API, then the problem is there isn't enough information.  People are sensitive to major bumps and we shouldn't bump major without knowing for sure imo but most dependencies are implementation details and a major bump should not be propagated. 

In the workspace context, one potential solution for this is to support the idea of a "shared" version where a relative version change (a bump) gets applied to the highest version among the shared and then set on all of them.  `cargo workspace` takes the opposite approach and shares by default and you have to declare a crate as "independent".  There is an accepted-but-not-implemented RFC that I hope to get to in the next year where you actually specify your version as "get it from the workspace's version".

Another approach is having some way to delineate what dependencies are in your public API and which ones are not, so we know which ones should cause breaking changes to propagate.  I've seen talk around this but I do not remember if there have been any cargo-native attempts at this problem,

**Comment by Byron** [comment]
> I feel like I'm not quite getting it from the image. What all is in a workspace vs not? Why, when bumping B does C not get updated to point to B2?

Right, sorry for that. It's entirely unclear that `C` is supposed to be workspace external, while `A` and `B` are within the workspace.

> If this is the situation I think it is, where A includes B in its API, then the problem is there isn't enough information. People are sensitive to major bumps and we shouldn't bump major without knowing for sure imo but most dependencies are implementation details and a major bump should not be propagated.

I agree, maybe such a feature should be limited to pre-release crates, _and be opt-in_. There I am happy to bump minor versions very frequently even if it's only to prevent breakage like stated above.

> In the workspace context, one potential solution for this is to support the idea of a "shared" version where a relative version change (a bump) gets applied to the highest version among the shared and then set on all of them. cargo workspace takes the opposite approach and shares by default and you have to declare a crate as "independent". There is an accepted-but-not-implemented RFC that I hope to get to in the next year where you actually specify your version as "get it from the workspace's version".

This sounds like a very interesting feature, even though it seems it can still cause unintended breakage as it would upgrade `B` to version 2 in the example above, which may break `C`s code on an automatic upgrade.
What I'd love to have is a way to prevent certain auto-updates if they lead to a situation like the one above. 

> Another approach is having some way to delineate what dependencies are in your public API and which ones are not, so we know which ones should cause breaking changes to propagate. I've seen talk around this but I do not remember if there have been any cargo-native attempts at this problem,

I don't know if it's similar enough to mention here, but `gitoxide` now has [stability tieres](https://github.com/Byron/gitoxide/blob/main/STABILITY.md#tiers), with the effective result of `git-repository` exposing all equally stable crates using re-exports. That way, nobody should have to pull in lower-level crates on their own. There is an `unstable` feature which exposes lower tier crates as well which would at least allow assure the same version is consistently used at the cost of being able to surprisingly break client code.

**Comment by Byron** [comment]
`cargo smart-release` now transitively bumps versions of dependent crates (unless this is disabled), leading to exactly what's described here. While at it, it now also creates only one commit for with all manifest adjustments, instead of one per crate to released (can be turned back to previous, single-crate release mode, too).

Here is how it looked like when bumping `git-traverse` due to breaking changes.

```text
Bump git-traverse v0.9.0, safety bump 8 crates

SAFETY BUMP: git-pack v0.12.0, git-diff v0.10.0, git-odb v0.22.0, git-transport v0.12.0, git-ref v0.8.0, git-packetline v0.11.0, git-protocol v0.11.0, gitoxide v0.9.0
```

The rule is such that if a to-be-published crate indicates a breaking change via semver, other pre-release crates depending on it do so transitively as well by having their version bumped. As production (i.e. major > 0) crates probably wouldn't like that, they get their minor version bumped instead. Downstream crates could use the `~1` version constraint to get patches only and avoid updating to feature releases.
