### ISSUE TITLE
git-ref: should non-existent prefix be an error?

### ISSUE THREAD

**Issue by kim** [Byron/gitoxide#202]
Another one on error handling :)

It turns out that `git_ref::file::Store::iter_prefixed` will return an error with message "The file system could not be traversed" if the prefix path doesn't exist in the loose refs. That's a bit surprising, because a. the prefix could still exist in the packed refs, and b. I would expect the prefix to behave like an optimisation, so not the entire refs tree needs to be scanned, and not a hard assertion. 

In that sense, should the iterator not just yield no elements in this case? Or am I holding this wrong somehow?

**Comment by Byron** [comment]
Sorry for that, it's a bug that is already fixed in #199, let me see if I can cherry-pick it into `main`.

**Comment by Byron** [comment]
The fix is in here: 293bfc02 , I think it's fair to merge the PR over and continue in a new one.

**Comment by Byron** [comment]
Alright, the fix is in main, the partial prefix will now work for loose refs as well.

**Comment by kim** [comment]
Thanks, looks good!
