### ISSUE TITLE
remove Argh/lean in favor of clap-only

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#215]
`cargo` uses `clap`, so can we… it's not worth having multiple code paths for that and it's better to focus on one ultimate commandline arg parser rather than distribute efforts. It's possible to shrink clap for sure.

This is the foundation for fixing the long-standing issue of the progress being drawn after the program output was printed. The latter is already fixed for `tui` based progress, and the same solution should then work for the standard progress, too.

**Comment by oknozor** [comment]
Hey I would be interested to pick this issue, to get familiar with the code base. Do you want clap only or clap with [structopt](https://github.com/TeXitoi/structopt) ?

**Comment by Byron** [comment]
Thanks for your interest! Maybe I can give you a boost with this illustration:

<img width="266" alt="Screen Shot 2021-12-03 at 8 05 26 AM" src="https://user-images.githubusercontent.com/63622/144522244-302844a5-7202-420e-92d3-8377cab2edae.png">

This issue isn't about implementing clap - it is available already - but removing the code path that uses `argh`. This work has already been performed for the porcelain CLI, but now needs to be done for the plumbing CLI as well.

I highly recommend following the [collaboration guide](https://github.com/Byron/gitoxide/blob/d8500043ab6b66335e9e09ba1706564a28421bbe/COLLABORATING.md#L1-L0), and if there are any additional questions, please let me know here or in the draft PR.

**Comment by oknozor** [comment]
Thank you, I will give it a shot.
