### ISSUE TITLE
Decide on a single terminal library

### ISSUE THREAD

**Issue by caspervonb** [Byron/gitoxide#217]
We have feature gates for termion and crossterm which is quite a bit of extra complexity (two source of bugs rather than just the one 😁 ).

Lets to dig into this a bit and determine which is preferable and remove the other code path (if any).

**Comment by caspervonb** [comment]
Unpopular opinion but, legacy windows doesn't matter anymore 😱
Windows 7 is already EOL and Windows 10 and onwards support escape sequences natively.

**Comment by Byron** [comment]
Independently of crossterms support for 'legacy' windows versions,  it's also actively developed whereas termion seems stale these days. Furthermore termion is on GitLab which probably prevents some contributions these days (I mean, they don't even merge their merge requests so it probably doesn't matter).

Unfortunately I can't check if this is still true as my network won't allow me to reach the server: https://gitlab.redox-os.org/redox-os/termion .
