### ISSUE TITLE
[Subcommand] gix status

### ISSUE THREAD

**Issue by danimesq** [Byron/gitoxide#255]

**Comment by Byron** [comment]
Since this user is proud of opening issues and created 4 zero effort issues within 2 minutes, I am closing this issue with similar effort while blocking the user from all interactions.

**Comment by inferiorhumanorgans** [comment]
@Byron So what are your thoughts on something equivalent to a `git status` command?  Specifically I'm interested in getting the status of an interactive rebase, something libgit2 cannot (currently) do.  Rather than dig into the C library I'd rather have a pure Rust library to use.  Unfortunately I'm not quite sure how this would all fit into the gitoxide crates since there doesn't seem to be any vestige of rebase status code.

https://github.com/libgit2/libgit2/issues/6127

**Comment by Byron** [comment]
Thanks for your interest. Handling interactive rebases currently isn't on the roadmap, but I would expect it to be no more than checking for specific files within `.git/`. Worktree status information is on the roadmap and should happen this year.

That said, there probably isn't much `gitoxide` can do for you now in relation to interactive rebase status, but I put it on the list of features to go for (5ee989360bb899e901bf29d735c9bb8004951fed).

**Comment by inferiorhumanorgans** [comment]
Yeah for the time being the information I'm interested in lives in `.git/rebase-merge/end` and `.git/rebase-merge/msgnum` and I'm just reading the files in.  It'd be nice to not reinvent the wheel, however.  My use case here is so that I can get repository status in a `bash` prompt, so most of what I'm doing with `libgit2` is just pulling metadata.

**Comment by inferiorhumanorgans** [comment]
I dug into this a little bit more today as neither `libgit2` nor `gitoxide` implement this completely.  The features I'm looking for are:

A way to check if there's an in-progress operation (e.g. rebase, cherry pick).  In `libgit2` this is `Repository::state()` and is accomplished by checking for the presence of various well-known files.  This is pretty darn simple (and I assume would fit into `git-repo`). I'm happy to open a PR if this all sounds about right.

The second is a way to get the target branch.  An interactive rebase leaves you with a detached head, but stores the target branch in `rebase-merge/head-name`, an in-progress cherry pick (e.g. with conflicts) leaves `HEAD` alone but `Head::referent_name()` chokes, etc.  Before hacking up `git-repo` too much I guess the big question is how the API should be shaped.  For e.g. a single function that checks in a variety of locations (i.e. `Repository::head()` or other), separate functions (e.g. `get_interactive_rebase_head`), or if should be rolled up into a higher level `get_rebase_state` kind of thing.

Lastly, as mentioned above getting access to the status of the rebase.

Cheers.

**Comment by Byron** [comment]
Thanks for digging in more!

> This is pretty darn simple (and I assume would fit into git-repo). I'm happy to open a PR if this all sounds about right.

I agree, and even if that opinion changes it's always possible to move an implementation around. That said, I also advise to read the git source code to be sure it truly is a simple as it seems. From my experience, git is deceptive, too.

> The second is a way to get the target branch.

I think it should be rebase-specific. If one queries what head points to it should always indicate the status quo. It's probably most straightforward to start with adding something like `interactive_rebase_head()` to keep it separated, eventually this can be picked up by something like `status()` as well.

In any case, please feel free to submit a draft PR and we can take it from there.

**Comment by Cypher1** [comment]
As I understand it `gitoxide` is supposed to be a `git` cli in Rust.
However, `gix` and `ein` do not seem to have support for the `status` subcommand and this (closed issue) is the only tracker for it.

Is that work tracked elsewhere or are the project's goals different to what I understood from the Readme?

**Comment by Byron** [comment]
Thanks for pointing this out.

I have added a section for `status` in the respective [tracking issue](https://github.com/Byron/gitoxide/issues/301). Getting there will take some time, but it's the issue you'd want to subscribe to.

**Comment by Cypher1** [comment]
Thanks. Also good to have a link here to point people there.
