### ISSUE TITLE
Some tests failing on main branch

### ISSUE THREAD

**Issue by oknozor** [Byron/gitoxide#268]
Hello, I am trying to get familiar with the project, running `make tests check-size` produce the following errors : 

```
running 9 tests
test commit::ancestor::instantiate_with_arc ... ok
test commit::ancestor::filtered_commit_does_not_block_ancestors_reachable_from_another_commit ... FAILED
test commit::ancestor::instantiate_with_box ... ok
test commit::ancestor::simple_branch_first_parent_only ... FAILED
test commit::ancestor::simple_branch_with_merge ... FAILED
test commit::ancestor::linear_history_no_branch ... ok
test commit::ancestor::predicate_only_called_once_even_if_fork_point ... FAILED
test commit::ancestor::multiple_tips ... FAILED
test tree::basic_nesting ... ok
```

Seems some object ids are not found in the store here : 
https://github.com/Byron/gitoxide/blob/3ab990ebbaf7feb999340e86933bbdc823166669/git-traverse/tests/commit/mod.rs#L48

I tried to understand what was going wrong but I am not sure how this works: 
https://github.com/Byron/gitoxide/blob/3ab990ebbaf7feb999340e86933bbdc823166669/git-traverse/tests/commit/mod.rs#L9

It is creating a fixture repository with some commit inside I get that, what I don't understand is how the object ids are set. I guess they are set somewhere since they are hard coded in the test.

**Comment by Byron** [comment]
Indeed it's executing [this script](https://github.com/Byron/gitoxide/blob/f0aeee1ca3d9c0fd1290c1912226c7dae396e10b/git-traverse/tests/fixtures/make_traversal_repo_for_commits.sh#L1-L0) to setup the repository. [Environment variables](https://github.com/Byron/gitoxide/blob/e276d777eb7a88dc424badbf88a929b5f567e5de/tests/tools/src/lib.rs#L87-L93) are set to assure this is reproducible.

However, it can still be affected by the local git configuration, which is why, for example, it has to turn off GPG signatures explicitly. Maybe there is something else that affects the commits being created. Do you have some git related global configuration or environment variables?

If so, it should be possible to adjust the calling code or the shell scripts themselves to fix this issue for good.

**Comment by oknozor** [comment]
I don't think I have any of these environment variables overridden.
Maybe in [my gitconfig](https://github.com/oknozor/dotfiles/blob/master/git/gitconfig), but I guess the environment variables takes precedence over this ?

Maybe I would be simpler to create the fixture commits in a helper function calling `std::process::Command` and retrieving the object ids afterward to use them in test assertions ? 
```rust
fn commit(message: &str) -> anyhow::Result<String> {
    Command::new("git")
        .arg("commit")
        .arg("--allow-empty")
        .arg("-m")
        .arf("-q")
        .arg(message)
        .stdout(Stdio::null())
        .stderr(Stdio::inherit())
        .output()?;

    let object_id = Command::new("git")
        .arg("log")
        .arg("--format=%H")
        .arg("-n")
        .arg("1")
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .output()?;

      String::from_utf8(output.stdout).map_err(|err| anyhow!(err))
}
```

Another way to have those test isolated from the user environment would be to run them in a docker container, I can add this if you want.

Also I think the `journey.sh` test suite could easily be replaced with a [bats](https://bats-core.readthedocs.io/en/stable/tutorial.html#your-first-test)  test suite running in docker. What do you think ?

**Comment by Byron** [comment]
> Maybe in my gitconfig, but I guess the environment variables takes precedence over this ?

Indeed, environment variables take precedence, and the git-config doesn't strike me as the root cause either. The `git` binary version is certainly relevant, but it's rather stable and I can only imagine that it won't pickup the DATE related configuration, using the current time instead of the given one.

I'd love to figure out what's happening there, also since it's seemingly only in `git-traverse`, not in all the other tests which use the same system.

For instance, here is how a simple generated test fixture looks like for me, how does it look like for you?

```
➜  git-repository git:(find-refactor) ✗ cd ../git-traverse/tests/fixtures/generated/1249043539
➜  1249043539 git:(main) tig
➜  1249043539 git:(main) git show
commit 85df34aa34848b8138b2b3dcff5fb5c2b734e0ce (HEAD -> main)
Author: author <author@example.com>
Date:   Sat Jan 1 00:00:00 2000 +0000

    c1
➜  1249043539 git:(main) git cat-file -p HEAD
tree 274459808c9c5b48c91834e25d8531056173a860
author author <author@example.com> 946684800 +0000
committer committer <committer@example.com> 946771200 +0000

c1
```

I find this system too practical and performant to rewrite it in Rust or run it in docker.

> Also I think the journey.sh test suite could easily be replaced with a bats test suite running in docker. What do you think ?

`utilities.sh` exists because there was nothing allowing to write BDD style tests for command-line applications. `bats` doesn't seem to be that.

**Comment by oknozor** [comment]
It looks the same for me : 

```
❯ git show
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
commit 85df34aa34848b8138b2b3dcff5fb5c2b734e0ce (HEAD -> main) ┃
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Author: author <author@example.com>
Date:   Sat Jan 1 00:00:00 2000 +0000

    c1


1249043539 on  main
❯ git cat-file -p HEAD
tree 274459808c9c5b48c91834e25d8531056173a860
author author <author@example.com> 946684800 +0000
committer committer <committer@example.com> 946771200 +0000

c1
```

```
❯ git --version                 
git version 2.34.1
```

I have no clue. 

Also I had some problems running tests in parallel on test generated repositories in [cocogitto](https://github.com/cocogitto/cocogitto). So  have been working on a little proc_macro attribute to run test involving git repositories in an forked process with a dedicated tmp directory. I don't know if you faced similar problem in gitoxide and I would be curious to know how you solved this. 

The attribute wrap the test with [`rusty_fork_test!`](https://docs.rs/rusty-fork/0.3.0/rusty_fork/macro.rusty_fork_test.html), and set the current directory of the forked process to a temp directory. 

 Maybe this would be interesting for gitoxide ? The end result look like this : 

```rust
    #[temp_test]
    fn get_latest_tag_ok() -> Result<()> {
        // Arrange
        let repo = Repository::init(".")?;
        run_cmd!(
            git commit -m "first commit" --allow-empty
            git tag 0.1.0
            git commit -m "second commit" --allow-empty
            git tag 0.2.0

        )?;

        // Act
        let tag = repo.get_latest_tag()?;

        // Assert
        assert_that!(tag.to_string_with_prefix()).is_equal_to("0.2.0".to_string());
        Ok(())
    }
```

**Comment by Byron** [comment]
That's great, as it means the generated repositories are as expected so the commit objects should be available. Maybe it's worth looking into `.git/objects` with `tree` just to be sure there isn't something special about the objects themselves. I'd expect a bunch of loose objects, maybe a pack.

> I don't know if you faced similar problem in gitoxide and I would be curious to know how you solved this.

The test system synchronizes access using a mutex, assuring the test script is executed only once before it's read potentially in parallel. For writing, it's copy-on-write.

> Maybe this would be interesting for gitoxide ? 

I think it's preferred to figure out what the problem is before trying to find solutions. Synchronization isn't the problem, because if it was the tests would work the second try. It's a read-only fixture, too, so nothing is copied around either.

This shows that maybe, the object format or object database format isn't understood so it doesn't find objects that are present. It might also be worth taking a look at `.git/config` to see if there is anything special. I'd also hope that looking into the `.git/objects` directory reveals the issue more clearly.

**Comment by oknozor** [comment]
Here it is :
```
gitoxide/.git/objects on  main
❯ tree
.
├── 1d
│   └── a00d6939eeb5d507c34756fd86b5c58e1feb52
├── 1f
│   └── 2483730d0818dc0e67858bc523fb1b427ece67
├── 21
│   └── 7da22d75193b5fc1ab625ad64181273c5ee08d
├── 2f
│   └── bcb55334c168bc70c0ff7cecf5da8e9d68cfd7
├── 39
│   └── d67b0b3fdcfc619b48424f46ea9857c7d98e35
├── 3f
│   └── ee691ec3ee24e7e29863cab8f9c861fa7647c8
├── 40
│   └── b2b41d7a0052eb487af117fc8ca72253a1787c
├── 58
│   └── 7c00a434a0cbe3ed325d5c422684a08edc596e
├── 61
│   └── f6c605e6b1e448c67dbbde00345b633c18cd24
├── 69
│   └── c6b1824208622aefb68558da6b448765362712
├── 6c
│   └── 53aa33b2dda026bfbe297836c540aafd9e1724
├── 6e
│   └── dcbac116cd38e7ae4129dddbca3f133eb3e0fd
├── 78
│   └── 6551f0f4a3aa8a9f38058b86863e37d30b521f
├── 80
│   └── b3bfba37a97ccae3b6298f42ca6d6edd9234ab
├── a4
│   └── f4b5211584ac3f57e13bbf9242092c25471b09
├── ac
│   ├── 681fa28573e0b296c992551fa7bcc56a3b550e
│   └── 9de9a2d8ec218233128b290534599733df8e87
├── b0
│   └── 616e2c46fa30c3b4418bcf4c320328f51bcf62
├── b6
│   └── e2f55f0c225946c5728d07cb73887d985a979f
├── ca
│   └── d88564128964c45f5848389b4d09236b1ffd17
├── cd
│   └── 7701e3c5268421c34fbf7858204e0cb4c0fa8c
├── info
└── pack
    ├── pack-9aefd5f6743e102dc7538cbf0858ec9748bbb51a.idx
    ├── pack-9aefd5f6743e102dc7538cbf0858ec9748bbb51a.pack
    ├── pack-a626a4a06d7a5f0f2256c3c91b7a4da56142f174.idx
    ├── pack-a626a4a06d7a5f0f2256c3c91b7a4da56142f174.pack
    ├── pack-d541e1e763aab89f50e3cdcdc3f5643177b9f4c7.idx
    └── pack-d541e1e763aab89f50e3cdcdc3f5643177b9f4c7.pack

22 directories, 27 files
```

```
gitoxide/.git on  main
❯ cat config
File: config
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    url = git@github.com:Byron/gitoxide.git
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
    remote = origin
    merge = refs/heads/main
```

**Comment by oknozor** [comment]
I think we have been looking at the wrong fixture. 
We  previously checked the generated fixtures in `/git-traverse/tests/fixtures/generated/1249043539` but when I run the test in 
`gitoxide/git-traverse/tests/commit` it generates `git-traverse/tests/fixtures/generated/1774415154`. 

- `1249043539` is the script identity for `make_traversal_repo_for_trees.sh`
- `1774415154` is the script identity for `make_traversal_repo_for_commits.sh`

Failing test resides in `gitoxide/git-traverse/tests/commit`. 

```
❯  git show
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
commit efd9a841189668f1bab5b8ebade9cd0a1b139a37 (HEAD -> main) ┃
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Author: author <author@example.com>
Date:   Sat Jan 1 00:00:00 2000 +0000

    c5
```
```
1774415154/.git/objects on  main 
❯ tree                
.
├── 13
│   └── 4385f6d781b7e97062102c6a483440bfda2a03
├── 17
│   └── d78c64cef6c33a10a604573fd2c429e477fd63
├── 4b
│   └── 825dc642cb6eb9a060e54bf8d69288fbee4904
├── 91
│   └── 52eeee2328073cf23dcf8e90c949170b711659
├── 95
│   └── 56057aee5abb06912922e9f26c46386a816822
├── 99
│   └── 02e3c3e8f0c569b4ab295ddf473e6de763e1e7
├── ce
│   └── 2e8ffaa9608a26f7b21afc1db89cadb54fd353
├── ef
│   └── d9a841189668f1bab5b8ebade9cd0a1b139a37
├── info
└── pack
```
```
❯ git cat-file -p HEAD
tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904
parent 9556057aee5abb06912922e9f26c46386a816822
author author <author@example.com> 946684800 +0000
committer committer <committer@example.com> 946771200 +0000

c5
```

**Comment by oknozor** [comment]
Alright the merge commit in the script is not working : 
```
❯ git log --pretty=format:'%Cred%H%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
efd9a841189668f1bab5b8ebade9cd0a1b139a37 - (HEAD -> main) c5 (22 years ago) <author>
9556057aee5abb06912922e9f26c46386a816822 - c4 (22 years ago) <author>
17d78c64cef6c33a10a604573fd2c429e477fd63 - c3 (22 years ago) <author>
9902e3c3e8f0c569b4ab295ddf473e6de763e1e7 - c2 (22 years ago) <author>
134385f6d781b7e97062102c6a483440bfda2a03 - c1 (22 years ago) <author>

1774415154 on  main 
❯ git merge branch1 -m m1b1                                                                                              
fatal: Not possible to fast-forward, aborting.
``` 
This was caused by my git config : 
```
[merge]
  tool = nvim
  ff = only
```
Removing `ff-only` I get the expected git log, except the merge commit object id is not what is expected in the tests. 
The sha1 in the test for the merge commit `m1b1` is `01ec18a3ebf2855708ad3c9d244306bc1fae3e9b`
and I end up with `24a3dab139f5b095c413f3c10f425824b22d86ff`, any idea ? 
```
❯ git log --pretty=format:'%Cred%H%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
24a3dab139f5b095c413f3c10f425824b22d86ff - (HEAD -> main) m1b1 (3 minutes ago) <Paul Delafosse>
efd9a841189668f1bab5b8ebade9cd0a1b139a37 - c5 (22 years ago) <author>
ce2e8ffaa9608a26f7b21afc1db89cadb54fd353 - (branch1) b1c2 (22 years ago) <author>
9556057aee5abb06912922e9f26c46386a816822 - c4 (22 years ago) <author>
9152eeee2328073cf23dcf8e90c949170b711659 - b1c1 (22 years ago) <author>
17d78c64cef6c33a10a604573fd2c429e477fd63 - c3 (22 years ago) <author>
9902e3c3e8f0c569b4ab295ddf473e6de763e1e7 - c2 (22 years ago) <author>
134385f6d781b7e97062102c6a483440bfda2a03 - c1 (22 years ago) <author>
```

**Comment by oknozor** [comment]
Alright I am stupid, I thought the generated fixture was recreated each time the tests are run. So I had the merge commit made manually with the wrong date and author. Cleaning everything and running the test again made it work !

**Comment by Byron** [comment]
Great, something to remember. There are probably more git options that affect how the test scripts are behaving. Maybe there is even one that can make git ignore the global configuration files.
