### ISSUE TITLE
[smart-release] no preview

### ISSUE THREAD

**Issue by jcornaz** [Byron/gitoxide#308]
I don't get any changelog preview when using `cargo smart-release` or `cargo changelog`.

I don't really know what to say to help understand the issue. So I'll only say that I am on linux and I have the  `EDITOR`  environment vairable set to `vim`.

Feel free to ask me more you need to know about my environment.

**Comment by jcornaz** [comment]
Ah... I finally got it. I had to install `bat`. Sorry for the noise :-/

**Comment by Byron** [comment]
No problem. It does leave a message about bat missing, but it's probably easy to overlook among all the output it can produce. Maybe there are better or more obvious ways, like using a warning instead.

**Comment by jcornaz** [comment]
Yes, it does leave the message. That's why I finally figured it out. But indeed, a warning level would probably be more appropriate.
