### ISSUE TITLE
oxidize `cargo-semver-checks`

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#313]
* [x] revparse-single()
* [x] checkout tree at revision

https://github.com/obi1kenobi/cargo-semver-checks

**Comment by Byron** [comment]
Thanks, @epage, for the initiative.

**Comment by epage** [comment]
>  checkout a ref

Note that this is specifically checking out a ref to an arbitrary directory and not to the working directory

>  probably diff of some sort

Unneeded, all diffing is on custom data structures derived from the two versions of the source

**Comment by Byron** [comment]
It looks like the project was archived and has been superseded by `cargo-semver-checks`.

**Comment by obi1kenobi** [comment]
I believe this might be safe to close, since `cargo-semver-checks` is fully oxidized and doesn't have `git2` in the dependency list anymore.

**Comment by Byron** [comment]
That's great to hear, thanks for letting me know :)!

If you have any ideas would you would like to see improved, please do let me know. I already saw that a stable release would be very nice, and it's something I really want to see one day as well.

**Comment by obi1kenobi** [comment]
Thank you for working on this! So far everything has been great, and I'm excited to see this project continue to grow 🚀
