### ISSUE TITLE
Unrecognized archive format gix-max-termion-git-tempfile-v1.0.6-aarch64-apple-darwin.tar.gz

### ISSUE THREAD

**Issue by davidmytton** [Byron/gitoxide#330]
Running the quick installer script fails on macOS 12.2 (Macbook Air M1 - ARM). Installing via `cargo` works fine.

```shell
# david @ dm-mba-m1 in ~ [11:12:57]
$ curl -LSfs https://raw.githubusercontent.com/Byron/gitoxide/main/ci/install.sh | \
    sh -s -- --git Byron/gitoxide --crate gix-max-termion
install.sh: GitHub repository: https://github.com/Byron/gitoxide
install.sh: Crate: gix-max-termion
install.sh: Tag: latest (git-tempfile-v1.0.6)
install.sh: Target: aarch64-apple-darwin
install.sh: Installing to: /Users/david/.cargo/bin
install.sh: Downloading: https://github.com/Byron/gitoxide/releases/download/git-tempfile-v1.0.6/gix-max-termion-git-tempfile-v1.0.6-aarch64-apple-darwin.tar.gz
tar: Error opening archive: Unrecognized archive format
```

**Comment by Byron** [comment]
This is a little bit of an unfortunate error message that caught me by surprise several times as well.

What happens is that the installer is unable to notice that the artifact it downloaded is empty. That empty file is then passed to the tar, who also fails to produce a more adequate message.

I think I know how to fix this.

**Comment by Byron** [comment]
In commit 65ce8c3498be1d158f78f9da810662ae830bfa0b there is additional instructions on how to use an alternative installation method, using `cargo quickinstall`. Even though it's not standalone the new instructions should help recover from the issue mentioned here.

Please take a look.

Even though I am closing this issue, maybe you see other options as well. If so, please don't hesitate to let me know. Ideally the `install.sh` script would be smarter, which could certainly be done.

**Comment by Byron** [comment]
PS: I have entirely removed `install.sh` as it can't work anymore unless it's properly fixed.

**Comment by davidmytton** [comment]
Thanks for looking at this. I get this error installing `quickinstall`

```shell
# david @ dm-mba-m1 in ~ [7:52:04]
$ cargo install quickinstall
    Updating crates.io index
error: could not find `quickinstall` in registry `crates-io` with version `*`
```

I think it needs to be `cargo install cargo-quickinstall`

Installing via `cargo install gitoxide` worked fine (once I had installed `cmake` via `brew` - maybe worth adding a note about that as a dependency when building from source).

**Comment by Byron** [comment]
Thanks for the feedback, I have updated the README once more. It's interesting that `cmake` is needed as it's apparently not required when building through `nix`.

I will look for a way to better document additional dependencies for building, for now I had to back off and postpone that though.
