### ISSUE TITLE
`ein` binary not generated after successful `cargo install`

### ISSUE THREAD

**Issue by hood** [Byron/gitoxide#347]
As title says, just ran `cargo install` (`cargo 1.61.0-nightly (ea2a21c 2022-02-15)`) on Arch Linux (`Linux arch 5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000 x86_64 GNU/Linux`), but no `ein` has appeared inside of my `~/.cargo/bin` folder. All I see are two new binaries named `gix` and `gixp`.

**Comment by Byron** [comment]
Thanks for letting me know. Indeed, a version of `gitoxide` with `ein` hasn't yet been published to crates.io, and one will see `gix` and `gixp` instead. For all intends and purposes, `ein` is `gix` and `gixp` is `gix`.

If you would like to install the latest version, `cargo install --git https://github.com/Byron/gitoxide` should do the job.

Does that help?

**Comment by fengzhyuan** [comment]
> cargo install --git https://github.com/Byron/gitoxide

Got the same issue, here's what I got:
```
cargo install --git https://github.com/Byron/gitoxide --force
    Updating git repository `https://github.com/Byron/gitoxide`
error: multiple packages with binaries found: c, c, cargo-smart-release, diffing, git-config-fuzz, git-testtools, git-tui, gitoxide, object-access, traversal. When installing a git repository, cargo will always search the entire repo for any Cargo.toml. Please specify which to install.
```

**Comment by Byron** [comment]
Thanks for trying it once again - it's something I would have noticed had I tried myself.

Here is a command-line that works, this time I validated it and updated the installation instructions in the README as well.

`cargo install --git https://github.com/Byron/gitoxide gitoxide`
