### ISSUE TITLE
Can't cross-compile for macOS due to missing libclang_rt.osx

### ISSUE THREAD

**Issue by giordano** [Byron/gitoxide#354]
I can't cross-compile gitoxide for macOS (both x86_64 and aarch64) from Linux due to missing `libclang_rt.osx`:
```
   Compiling gitoxide v0.11.0 (/workspace/srcdir/gitoxide)
error: linking with `x86_64-apple-darwin14-cc` failed: exit status: 1
  |
  = note: "x86_64-apple-darwin14-cc" "-m64" "-arch" "x86_64" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/deps/ein-9fcae47b1b1ebf08.ein.47f3b811-cgu.0.rcgu.o" "-L" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/deps" "-L" "/workspace/srcdir/gitoxide/target/release/deps" "-L" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/build/libz-sys-e50b34a092513fc3/out/lib" "-L" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/build/sha1-asm-17d1a73b0a1fdaa2/out" "-L" "/opt/x86_64-linux-musl/lib/clang/12.0.0:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../../../x86_64-linux-musl/lib/../lib64:/lib/../lib64:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../../../x86_64-linux-musl/lib:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../..:/opt/x86_64-linux-musl/bin/../lib:/lib:/usr/lib/lib/darwin" "-L" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/build/curl-sys-5d11ec0149c77c5f/out/build" "-L" "/opt/x86_64-linux-musl/toolchains/1.59.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-apple-darwin/lib" "/tmp/rustcshiXmK/libcurl_sys-fa0120d2dd0da2d8.rlib" "/tmp/rustcshiXmK/liblibz_sys-e80e1d7cc665ff85.rlib" "/tmp/rustcshiXmK/libsha1_asm-9ec8770893789a16.rlib" "/opt/x86_64-linux-musl/toolchains/1.59.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-340138346aaa8364.rlib" "-lclang_rt.osx" "-framework" "Security" "-framework" "CoreFoundation" "-framework" "SystemConfiguration" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/opt/x86_64-linux-musl/toolchains/1.59.0-x86_64-unknown-linux-musl/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/workspace/srcdir/gitoxide/target/x86_64-apple-darwin/release/deps/ein-9fcae47b1b1ebf08" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: warning: directory not found for option '-L/opt/x86_64-linux-musl/lib/clang/12.0.0:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../../../x86_64-linux-musl/lib/../lib64:/lib/../lib64:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../../../x86_64-linux-musl/lib:/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/5.2.0/../../..:/opt/x86_64-linux-musl/bin/../lib:/lib:/usr/lib/lib/darwin'
          ld: library not found for -lclang_rt.osx
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
I see that on macOS there is a static library `libclang_rt.osx.a`, but this isn't shipped by the SDK which can be used for cross-compilation from Linux, that one only has the stub `*.tbd` libraries.

I'm also not sure why the list of directories is passed like that to `-L` instead of using multiple `-L`, but that's probably unrelated.

**Comment by Byron** [comment]
Thanks for letting me know, I wasn't aware.

I wonder to what extend this is a general problem or one that is specific to `gitoxide`. If it's the latter, I wouldn't know what to do to fix it, but if it's the former, I wonder if there is another place to address the issue?

Thanks for sharing your thoughts on this.

**Comment by giordano** [comment]
We've built a few other rust packages in [Yggdrasil](https://github.com/JuliaPackaging/Yggdrasil) using [BinaryBuilder](https://binarybuilder.org/) and gitoxide has been the first one presenting this issue. It definitely isn't that widespread

**Comment by Byron** [comment]
Thanks for the clarification. Maybe it's due to its dependencies, some of which might link to system libraries.

Can you try something equivalent to `cargo build --no-default-features --features small`? That will build a pure Rust version, and drop as many C libraries as possible. If that works, you could probably figure out which dependency might be causing this by looking at the differences in the dependency trees and cargo features.

Thanks for your help.

**Comment by giordano** [comment]
Ok, I managed to compile the LLVM runtime libraries for the target system, including `libclang_rt.osx.a`.  With that I was able to cross compile gitoxide for macOS, so I'm going to close this issue.  Thanks anyway for the prompt replies!
