### ISSUE TITLE
Can't build for 32-bit platforms

### ISSUE THREAD

**Issue by giordano** [Byron/gitoxide#355]
```
error: any use of this value will cause an error
   --> git-bitmap/src/ewah.rs:114:46
    |
114 |     const RLW_LARGEST_RUNNING_COUNT: usize = (1 << RLW_RUNNING_BITS) - 1;
    |     -----------------------------------------^^^^^^^^^^^^^^^^^^^^^^^-----
    |                                              |
    |                                              attempt to shift left by `32_usize`, which would overflow
    |
    = note: `#[deny(const_err)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
```
https://github.com/Byron/gitoxide/blob/7e76796d5c2956961bd998286bec05fca1ba8fc4/git-bitmap/src/ewah.rs#L114

**Comment by Byron** [comment]
I believe to have fixed the issue, could you try again?

**Comment by giordano** [comment]
Sorry for getting long to get back to this, but I can confirm now I can build for i686, thanks!  Unfortunately compilation still fails for armv6l/armv7l, but that's because these platforms aren't supported by `sha1-asm`, so it's unrelated to this package.  Thanks again!

**Comment by Byron** [comment]
No worries!

You should be able to build it using `--no-default-features --features small` to essentially use only Rust libraries for zlib and sha-1. This will be a non-parallel build as well but could serve as a starting point to selectively add additional capabilities like parallelism and faster zlib libraries, avoiding only `sha1-asm` eventually.
