### ISSUE TITLE
Question: Does gitoxide has improvements from https://vfsforgit.org/

### ISSUE THREAD

**Issue by pparikhatliaison** [Byron/gitoxide#38]
I just found this project today and have a question does gitoxide already have the improvements suggested and made in VFS for git?

**Comment by Byron** [comment]
No, it doesn’t.

Please note I couldn’t check the website as it’s certificate was expired for 42 days.

**Comment by bkhl** [comment]
I assume that's the same as https://github.com/Microsoft/VFSForGit

**Comment by Byron** [comment]
Yes, it's definitely enough to get an understanding. From what I see, there is the VFS portion which runs on windows, along with a modified version (maybe these are upstream already) of git that avoids doing any unnecessary IO calls.
If care is taken and once shallow/sparse (?) checkouts are supported here, at least in theory VFS should work just as well. After all it modifies the repository's data structures directly, affecting each git or gitoxide invocation accordingly.

Once this implementation is feature-complete enough, it would definitely be worth trying out.

**Comment by pparikhatliaison** [comment]
@Byron do you want to keep this open?  Now that you have good understanding and it seems like it is an enhancement.

**Comment by Byron** [comment]
Great to hear! The issue was closed a while ago, and I think it can be posted again once a little more of the required features are available.

**Comment by pparikhatliaison** [comment]
@Byron , sounds good.
