### ISSUE TITLE
[git-config][bug] parser fails on underscores

### ISSUE THREAD

**Issue by mzr** [Byron/gitoxide#404]
The parser doesn't handle undersores (`_`) well:

```
use git_config::file::GitConfig;
use anyhow::Result;

fn main() -> Result<()> {

        let conf = r#"
            [a_b]
                ab = b
        "#;

        let _: GitConfig = conf.try_into()?;

    Ok(())
}
```

gives:

```
➜  gitconfig git:(master) ✗ cargo run
   Compiling gitconfig v0.1.0 (/home/mzr/sources/gitconfig)
    Finished dev [unoptimized + debuginfo] target(s) in 0.58s
     Running `target/debug/gitconfig`
Error: Got an unexpected token on line 2 while trying to parse a section header: '[a_b]
    ' ... (27 characters omitted)
```

**Comment by Byron** [comment]
Thanks a lot for the initiative!

Trying the same with git yields the same results though, underscores are rejected…

<img width="192" alt="Screen Shot 2022-05-06 at 07 16 45" src="https://user-images.githubusercontent.com/63622/167042378-ed2a4802-a532-4fca-8bf4-501de505e421.png">

…with something like this: `fatal: bad config line 35 in file .git/config`.

Thus the parser is handling it exactly according to spec, and there is no incentive to make it more flexible than the parser git uses as `gitoxide` cannot cause incompatibility to `git` in any way.

Thanks for your understanding.
