### ISSUE TITLE
[git-sec] adopt git-for-windows quirks

### ISSUE THREAD

**Issue by davidkna** [Byron/gitoxide#424]
### Summary 💡

Git-for-Windows has some exceptions for the ownership checks. The home directory is accepted unconditionally (which is owned by admin instead of the user), and admin-group-owned folders are accepted if the user is an admin (helpful in environments like Github-Actions).

Git-for-Windows references:
https://github.com/git-for-windows/git/blob/0cd1496fc3dd78dadbdf3644ec4d384188573e6f/compat/mingw.c#L3503-L3515

https://github.com/git-for-windows/git/blob/0cd1496fc3dd78dadbdf3644ec4d384188573e6f/compat/mingw.c#L3535-L3543

If this is something you would be happy to adopt, I would be happy to make a contribution

### Motivation 🔦

* Allow opening repos in home directory on Windows
* Allows the check to work in GHA without extra workarounds

**Comment by Byron** [comment]
> If this is something you would be happy to adopt, I would be happy to make a contribution

Yes, `gitoxide` would love to act similarly on Windows.

#### _For context_

When I implemented this, I intentionally left out the special case related to the admin home as `gitoxide` implements much finer grained control over what's permitted in a repository. By default, even with reduced Trust, typical repositories are readable and even writable without hickups. `gitoxide` will implement additional safe-guards by associating trust with configuration values, which is how it can say that 'we want executable paths only if we own the file containing it (or we deem it OK for other reasons)'. That way attacker-controlled configuration or files will simply be ignored while falling back to configuration or files which are trusted.

However, as it also implements the strictly optional [full-bailout](https://github.com/Byron/gitoxide/blob/a7ac64cd801b985790b5717be1a5dc722b2ae3a9/git-repository/src/open.rs#L231-L234) like git, it would definitely be beneficial to implement the same logic to determine trust on windows as git does.

**Comment by davidkna** [comment]
closed via https://github.com/Byron/gitoxide/pull/426
