### ISSUE TITLE
Linked gitdirs without commondir file (submodules) don't resolve git dir

### ISSUE THREAD

**Issue by davidkna** [Byron/gitoxide#482]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

This causes starship/starship#4266

If a linked git dir does not contain a `commondir` file, it will be ignored: https://github.com/Byron/gitoxide/blob/47724c0edb382c036a3fc99884becfd2b0740d4b/git-discover/src/is.rs#L43-L48

I tried replacing it with this, but that caused some test failures I wasn't sure how to best resolve:
```rust
            let common_dir = private_git_dir.join(common_dir);
                .and_then(Result::ok)
                .map(|cd| private_git_dir.join(cd))
                .unwrap_or_else(|| private_git_dir.clone());
````

This means that for git submodules, the git dir ends up resolving to `mysubmodule/.git` instead of `.git/modules/mysubmodule`.

### Expected behavior 🤔

Git submodule `.git`-files resolve to the referenced location.

### Steps to reproduce 🕹

1. Attempt to open a submodule directory
2. Inspect `.git_dir()`

**Comment by Byron** [comment]
Thanks a lot! It would have been lucky if this would have worked out of the box, as it was never tested.

This should change though, and I plan to remedy this soon, hoping that a test or two with submodules can help making the necessary adjustments without having to support submodules fully. Let's see :D.
