### ISSUE TITLE
`git_hash::ObjectId::from_hex` can panic from user input

### ISSUE THREAD

**Issue by Nemo157** [Byron/gitoxide#522]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Attempting to construct a `git_hash::ObjectId` from a non-hex string panics.

### Expected behavior 🤔

An error should be returned.

### Steps to reproduce 🕹

```rust
fn main() {
    let _ = git_hash::ObjectId::from_hex(b"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");
}
```

```console
> cargo run
thread 'main' panicked at 'our length check is correct thus we can decode hex: InvalidHexCharacter { c: 'z', index: 0 }', crates.io/git-hash-0.9.8/src/lib.rs:49:50
```

**Comment by Byron** [comment]
The fix was released with [v0.9.9](https://github.com/Byron/gitoxide/releases/tag/git-hash-v0.9.9).
