### ISSUE TITLE
test upwards::from_dir_with_dot_dot fails when within a worktree

### ISSUE THREAD

**Issue by paulyoung** [Byron/gitoxide#544]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When running `make tests check-size` in a worktree, the test `upwards::from_dir_with_dot_dot` fails:

```
---- upwards::from_dir_with_dot_dot stdout ----
thread 'upwards::from_dir_with_dot_dot' panicked at 'assertion failed: `(left == right)`
  left: `WorkTree { linked_git_dir: Some("/Users/py/projects/Byron/gitoxide/main/.git/worktrees/reproduce-test-failure") }`,
 right: `WorkTree { linked_git_dir: None }`', git-discover/tests/upwards/mod.rs:85:5
```

### Expected behavior 🤔

The test should pass, as it does on the `main` branch.

### Steps to reproduce 🕹

1. `mkdir -p ~/projects/Byron/gitoxide`
2. `git clone git@github.com:Byron/gitoxide.git ~/projects/Byron/gitoxide/main`
3. `cd ~/projects/Byron/gitoxide/main`
4. `make tests`
5. `git branch reproduce-test-failure`
6. `mkdir ../reproduce-test-failure`
7. `git worktree add ../reproduce-test-failure reproduce-test-failure`
8. `cd ../reproduce-test-failure`
9. `make tests`

**Comment by Byron** [comment]
Thanks a lot! I was able to reproduce it thanks to your instructions, and will release a fix soon.
I think this is the _one_ test that relies on being in a parent repository and it without my knowledge relied on the fact that this is not a worktree. I think I can make that assumption wider or have it skip the test if it's not starting out where it should be.

Of course the real fix would be to not rely on the parent repo at all, but… let's see :D.
