### ISSUE TITLE
`cargo-smart-release` typo in changelog commit statistics

### ISSUE THREAD

**Issue by mattcl** [Byron/gitoxide#560]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Thanks again for this utility. The commit statistics in the generated changelogs contain messages like `- 0 issues like '(#ID)' where seen in commit messages`, and they should likely be `- 0 issues like '(#ID)' were seen in commit messages` (replacing `where` -> `were`).

### Steps to reproduce 🕹

I expect all currently generated changelogs to have this message in the event of zero messages meeting the `#ID` criteria.

**Comment by Byron** [comment]
Thanks for bringing this to my attention - amazing a blatant error like this survived this long.

That said, I have pushed the fix in the latest main and it will be coming with the next release in a couple of days. Once changelogs are regenerated, on the next publish for instance, they will fix themselves. Please note that this isn't true for changelogs placed into annotated tags or onto the GitHub releases page.

**Comment by Byron** [comment]
Closing as it's fixed in `main` and a release is pending.
