### ISSUE TITLE
clone API fails if branch name contains a /

### ISSUE THREAD

**Issue by AaronDewes** [Byron/gitoxide#571]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Gitoxide panics when cloning a repository with branches that contain a `/` character.

```
thread 'main' panicked at 'slice index starts at 11 but ends at 6', library/core/src/slice/index.rs:92:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior 🤔

Cloning should work properly.

### Steps to reproduce 🕹

This repository contains a branch with a / in the name. The main branch clones the repository and demonstrates the bug (`cargo run`): https://github.com/AaronDewes/gitoxide-bug-demo

**Comment by Byron** [comment]
Thanks a lot for filing this issue and making it easy to reproduce.

I was able to reproduce it with `RUST_BACKTRACE=1 gix remote -n "https://github.com/AaronDewes/gitoxide-bug-demo" ref-map 'refs/heads/*:refs/remotes/origin/*'` and think a fix should be available in `main` soon.

For completeness, here is the backtrace:

```
thread 'main' panicked at 'slice index starts at 11 but ends at 6', library/core/src/slice/index.rs:92:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_index_order_fail_rt
   3: core::ops::function::FnOnce::call_once
   4: core::intrinsics::const_eval_select
   5: core::slice::index::slice_index_order_fail
   6: git_refspec::match_group::util::Needle::to_bstr_replace
   7: git_refspec::match_group::util::Matcher::matches_lhs
   8: git_repository::remote::connection::ref_map::<impl git_repository::remote::connection::Connection<T,P>>::ref_map_inner
   9: gix::plumbing::main::main::{{closure}}
  10: gix::plumbing::main::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
