### ISSUE TITLE
`cargo audit` oxidization

### ISSUE THREAD

**Issue by Shnatsel** [Byron/gitoxide#573]
### Summary 💡

Repository: https://github.com/rustsec/rustsec

- [x] Network transport implementation in Rust, `rustls` as the TLS implementation #530
- [x] `crates-index` uses gitoxide https://github.com/frewsxcv/rust-crates-index/issues/82

### Motivation 🔦

We need to get rid of memory-unsafe code that interfaces with the network, chiefly OpenSSL.

It's ironic to have a tool for discovering CVEs in your code use OpenSSL itself, especially when `rustls` exists.

### Implementation

* https://github.com/rustsec/rustsec/pull/922

**Comment by Byron** [comment]
Is this completed? I think it might, but thought I ask before closing. Thank you.

**Comment by Shnatsel** [comment]
Yes!
