### ISSUE TITLE
IOS Support -and more generally any rust target + headache-free cross compiling VIA using native rust libs

### ISSUE THREAD

**Issue by colbyn** [Byron/gitoxide#575]
### Summary 💡

Add a feature to use native rust libraries for cases where optimized C libs become a huge headache or refuse to build, such as when cross compiling to IOS. 

### Motivation 🔦

In #122 someone remarked

> Just a heads-up, we decided on using zlib-ng over a native rust implementation due to the large performance benefits; you can see the discussion in #47. 

The problem with `zlib-ng` is that it becomes problematic when cross-compiling to e.g. IOS, whereas native rust code tends to be headache free.

**Comment by Byron** [comment]
Thanks for the suggestion!

In case it matters, one can get a (probably close to) Rust-only build with `cargo build --no-default-features --features small`, or the respective features it sets in the `git-features` crate. As far as I know there is no way to know if a crate uses a C compiler in its build scripts or does anything else non-Rusty. Maybe I am missing something though.

**Comment by colbyn** [comment]
@Byron the current issue I have is compiling `libz-sys`, 

<details>
<summary>Here is the log if you want to see it</summary>
<pre>error: failed to run custom build command for `libz-sys v1.1.8`

Caused by:
  process didn't exit successfully: `/Users/colbyn/Projects/subscript-root/target/release/build/libz-sys-f3ff5c4f94c5a6e0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-ios = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_ios = None
  TARGET_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-ios = None
  CMAKE_GENERATOR_aarch64_apple_ios = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  running: "xcrun" "--show-sdk-path" "--sdk" "iphoneos"
  exit status: 0
  CMAKE_PREFIX_PATH_aarch64-apple-ios = None
  CMAKE_PREFIX_PATH_aarch64_apple_ios = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-ios = None
  CMAKE_aarch64_apple_ios = None
  TARGET_CMAKE = None
  CMAKE = None
  running: "cmake" "/Users/colbyn/.cargo/registry/src/github.com-1ecc6299db9ec823/libz-sys-1.1.8/src/zlib-ng" "-DCMAKE_OSX_SYSROOT=/" "-DCMAKE_OSX_DEPLOYMENT_TARGET=" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_SYSTEM_NAME=iOS" "-DCMAKE_SYSTEM_PROCESSOR=arm64" "-DCMAKE_INSTALL_PREFIX=/Users/colbyn/Projects/subscript-root/target/aarch64-apple-ios/release/build/libz-sys-01ca867cadfc297d/out" "-DCMAKE_C_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -fembed-bitcode" "-DCMAKE_C_COMPILER=/usr/bin/clang" "-DCMAKE_CXX_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -fembed-bitcode" "-DCMAKE_CXX_COMPILER=/usr/bin/clang++" "-DCMAKE_ASM_FLAGS= -fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -fembed-bitcode" "-DCMAKE_ASM_COMPILER=/usr/bin/clang" "-DCMAKE_BUILD_TYPE=Release"
  -- Using CMake version 3.24.2
  -- ZLIB_HEADER_VERSION: 1.2.11
  -- ZLIBNG_HEADER_VERSION: 2.1.0.devel
  -- Configuring incomplete, errors occurred!
  See also "/Users/colbyn/Projects/subscript-root/target/aarch64-apple-ios/release/build/libz-sys-01ca867cadfc297d/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/Platform/iOS-Initialize.cmake:4 (message):
    / is not an iOS SDK
  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
    CMakeLists.txt:37 (project)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /Users/colbyn/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace</pre>
</details>

Looking at [gitoxide/git-features/Cargo.toml](https://github.com/Byron/gitoxide/blob/main/git-features/Cargo.toml#L55) I see this line
```toml
## available for completeness even though it's the default - it may be chosen for more specific feature flag names, instead of a bare `zlib`.
zlib-rust-backend = ["flate2/rust_backend"]
```

But it's not available from e.g. `git-repository = "0.25.0"`, do you know how I could activate this feature? I was about to  fork this whole project but not doing this would be super convenient.

**Comment by colbyn** [comment]
Also usually ssl is another issue where I'd rather use `rustls` over e.g. `openssl` whenever such becomes problematic.

**Comment by colbyn** [comment]
Oh I got to build for IOS! 🙂

Specifically, 
```
➜ cargo build --release --target aarch64-apple-ios
```

Note that, for open-ssl, you have to use the `vendored` flag, e.g:
```toml
[dependencies.openssl-sys]
features = ['vendored']
```

I'm thinking for now, I'll publish the following crates with an IOS prefix, 
```
ios-git-url
ios-git-hash
ios-git-validate
ios-git-ref
ios-git-command
ios-git-config
ios-git-config-value
ios-git-discover
ios-git-features
ios-git-commitgraph
ios-git-chunk
ios-git-quote
ios-git-object
ios-git-glob
ios-git-diff
ios-git-date
ios-git-traverse
ios-git-index
ios-git-bitmap
ios-git-worktree
ios-git-revision
ios-git-packetline
ios-git-mailmap
ios-git-note
ios-git-fetchhead
ios-git-prompt
ios-git-filter
ios-git-sec
ios-git-lfs
ios-git-rebase
ios-git-sequencer
ios-git-submodule
ios-git-transport
ios-git-credentials
ios-git-protocol
ios-git-pack
ios-git-odb
ios-git-tempfile
ios-git-lock
ios-git-attributes
ios-git-pathspec
ios-git-refspec
ios-git-path
ios-git-repository
ios-gitoxide-core
ios-git-tui
ios-git-tix
```

Although it also works for MacOS, so maybe something like this makes more sense for cases where you want both to just seamlessly work:
```
git-url-for-macos-ios
git-hash-for-macos-ios
git-validate-for-macos-ios
git-ref-for-macos-ios
git-command-for-macos-ios
git-config-for-macos-ios
git-config-value-for-macos-ios
git-discover-for-macos-ios
git-features-for-macos-ios
git-commitgraph-for-macos-ios
git-chunk-for-macos-ios
git-quote-for-macos-ios
git-object-for-macos-ios
git-glob-for-macos-ios
git-diff-for-macos-ios
git-date-for-macos-ios
git-traverse-for-macos-ios
git-index-for-macos-ios
git-bitmap-for-macos-ios
git-worktree-for-macos-ios
git-revision-for-macos-ios
git-packetline-for-macos-ios
git-mailmap-for-macos-ios
git-note-for-macos-ios
git-fetchhead-for-macos-ios
git-prompt-for-macos-ios
git-filter-for-macos-ios
git-sec-for-macos-ios
git-lfs-for-macos-ios
git-rebase-for-macos-ios
git-sequencer-for-macos-ios
git-submodule-for-macos-ios
git-transport-for-macos-ios
git-credentials-for-macos-ios
git-protocol-for-macos-ios
git-pack-for-macos-ios
git-odb-for-macos-ios
git-tempfile-for-macos-ios
git-lock-for-macos-ios
git-attributes-for-macos-ios
git-pathspec-for-macos-ios
git-refspec-for-macos-ios
git-path-for-macos-ios
git-repository-for-macos-ios
gitoxide-core-for-macos-ios
git-tui-for-macos-ios
git-tix-for-macos-ios
```

**Comment by colbyn** [comment]
Also my fork is [over here](https://github.com/colbyn/gitoxide-use-native-deps) if anyone wants to see it, it's kinda messy though, I basally just ripped out a few things and updated some hardcoded stuff.

**Comment by Byron** [comment]
> But it's not available from e.g. git-repository = "0.25.0", do you know how I could activate this feature? I was about to fork this whole project but not doing this would be super convenient.

Indeed, and in [this comment](https://github.com/Byron/gitoxide/issues/530#issuecomment-1301087886) I describe how feature toggles can be configured from the users crate. In this case one probably wants to set `default-features = false` for `git-repository` as well to be able to configure `git-features` similar to how `git-transport` is configured in the linked comment.

> Oh I got to build for IOS! 🙂

Great to hear! I think now we could focus on figuring what's needed to port this back to this project so that…

1. users can build `gitoxide` on `ios`
2. CI builds on IOS to protect from regressions

Regarding 1), I it seems we need to figure out why `openssl` slips into the dependency tree and if it can be made optional/turned off entirely. If not, `gitoxide` might want to force the configuration to vendored. However, I hope there is a way to build `gitoxide` without openssl for obvious reasons. When running `cargo tree -i openssl-sys` on the `max` configuration, there was no result, so `libcurl` seems to depend on it implicitly/using C linking.

**Comment by colbyn** [comment]
Also I think `gitoxide` will be compelling over `libgit2` for IOS since GPL code is technically banned on the App Store.

Although I believe there is a linking exception for `libgit2`, I don't know the ramifications of it, but regardless `gitoxide` is MIT...

**Comment by colbyn** [comment]
Oh actually this isn't needed:
```toml
[dependencies.openssl-sys]
features = ['vendored']
```

All I needed was
```toml
[dependencies]
libz-sys = "1.1.8" # For some reason this dependency needs to be explicitly defined to build for aarch64-apple-ios
git-repository = { version = "^0.25.0", features = ["blocking-network-client"] }
git-transport-for-configuration-only = { version = "^0.21.0", package = "git-transport", features = ["http-client-reqwest"] }
```

Then running `cargo build --release --target aarch64-apple-ios` compiles.

I'll report any issues I get when linking the rust static lib from Xcode, but everything seems to be working so I think I can close this. 🙂

**Comment by Byron** [comment]
Amazing! So good to hear it works and thanks a lot for leaving your findings for others to benefit.

Maybe some time we will even understand what to do about that unexpected `libz-sys` dependency.

**Comment by holzschu** [comment]
> Oh actually this isn't needed:
> 
> ```toml
> [dependencies.openssl-sys]
> features = ['vendored']
> ```
> 
> All I needed was
> 
> ```toml
> [dependencies]
> libz-sys = "1.1.8" # For some reason this dependency needs to be explicitly defined to build for aarch64-apple-ios
> git-repository = { version = "^0.25.0", features = ["blocking-network-client"] }
> git-transport-for-configuration-only = { version = "^0.21.0", package = "git-transport", features = ["http-client-reqwest"] }
> ```
> 
> Then running `cargo build --release --target aarch64-apple-ios` compiles.
> 
> I'll report any issues I get when linking the rust static lib from Xcode, but everything seems to be working so I think I can close this. 🙂

Hi @colbyn, 
which file exactly did you change to add these lines in order to compile for iOS? Somehow it doesn't seem to work for me.

**Comment by Byron** [comment]
These are very old and it's now called `gix-*`. The top-level crate you probably want to use is `gix` and it can be configured from there with feature toggles.

If I were you, I'd try to compile `gitoxide` for IOS with `--no-default-features --feature max-pure` - that will create a pure Rust build which should be easiest to get to work.
The feature toggles behind that can be inspected in `Cargo.toml`, and then be applied to the underlying `gix` crate.

More documentation for that [is here](https://github.com/Byron/gitoxide/pull/1383) and [here](https://docs.rs/gix/latest/gix/#feature-flags).

Please do share your findings here :).

**Comment by holzschu** [comment]
I can report that `cargo build --target aarch64-apple-ios --no-default-features --features max-pure` does compile with a clone of the current repository and produces an iOS executable. Thank you very much. 

Now I have to figure out how to make it a dynamic library instead of an executable, but that's not a gitoxide issue.

**Comment by NobodyXu** [comment]
> Now I have to figure out how to make it a dynamic library instead of an executable, but that's not a gitoxide issue.

For that, you could pull in gitoxide in a new cargo project, and compile it as a dynamic library.

You could then copy the files in https://github.com/Byron/gitoxide/tree/main/src to your dynamic libraries and declare them as a module in your `lib.rs`.

You can then export these renamed `main` functions as C function using

```rust
#[no_mangle]
pub extern "C" fn gix_main() {
    gix::main()
}
```
