### ISSUE TITLE
Cloning linux from kernel.org fails

### ISSUE THREAD

**Issue by pascalkuthe** [Byron/gitoxide#577]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Cloning the linux kernel from `kernel.org` instead of from github fails.
When using the git porotocol, the following error is produced:
```
Error: An IO error occurred when talking to the server

Caused by:
    access denied or repository not exported: /pub/scm/linux/kernel/git/torvalds/linux.git
```

Cloning using `https` fails with 
```
Error: Expected to see "# service=git-upload-pack", but got "version 2\nagent=git/2.31.1\nls-refs=unborn\nfetch=shallow\nserver-option\nobject-format=sha1"`
```

### Expected behavior 🤔

Cloning the repository succedes (using both protocols).

### Steps to reproduce 🕹

Execute either
`gix clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux`
or
`gix clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux`

Both commands succeed with git.
I am not sure these issues are related but since they pertain to the same server I posted them together.
Cloning from other servers with these protocols work (`https` works for github and gitlab, `git` works for sourceforge) so its something specific to `kernel.org`.

**Comment by pascalkuthe** [comment]
This is partiall fixed by #578. It turns out that these are two seperate issues.
Fixing the git connection was easy but the https problem seems more complicated

**Comment by Byron** [comment]
Thanks a lot for reporting, and debugging this issue and fixing it partially, I appreciate your time (tremendously)!

I will take a quick look at the HTTP protocol issue in the hopes to get lucky.

**Comment by pascalkuthe** [comment]
The server is returning something completely unexpected (in `client/blocking_io/http/mod.rs:235`).
Capturing HTTPS traffic is not possible and `kernel.org` rejects http traffic so I have no idea whats going on :(

**Comment by Byron** [comment]
I am actually looking at a proxied response right now so a fix is nigh :D. Using Proxyman on MacOS + [this line](https://github.com/Byron/gitoxide/blob/943fd153a2daca25c0e716388c528a83ad43be95/git-transport/src/client/blocking_io/http/curl/remote.rs#L121) make it possible.

**Comment by Byron** [comment]
This works in `main` now, thanks again for all your help!
