### ISSUE TITLE
More high-level documentation

### ISSUE THREAD

**Issue by seanaye** [Byron/gitoxide#591]
### Summary 💡

I have found the gitoxide-core crate and have been successfully able to do `git init` but I'm having trouble figuring out other standard git commands

e.g.
`git add` - seems to be missing in docs
`git commit` - Docs have a commit describe fn but I don't think thats to create a new commit
`git push` - also seems to be missing

It would be great if there was a simple list of common git commands and their function documentation

Thanks for your work on this crate!

### Motivation 🔦

I want to embed git and use it programmatically in a tauri app im working on

**Comment by Byron** [comment]
Very exciting, I also would use Tauri for a GUI app.

In commit e9f83ee the `gitoxide-core` documentation was updated directly discourage using this crate and use `git-repository` instead.

> It would be great if there was a simple list of common git commands and their function documentation

I agree, and plan to create examples for common operations, one for each, to be found in `git-repository/examples`, and most certainly as doc-tests as well. I am tracking this [in this newly created card](https://github.com/Byron/gitoxide/projects/2#card-86737940).

Closing this issue as improving the documentation and gaining more users isn't planned yet.
