### ISSUE TITLE
License issue: docs copied from git into MIT-licensed project

### ISSUE THREAD

**Issue by joshtriplett** [Byron/gitoxide#6]
https://github.com/Byron/gitoxide/commit/069b3126ddb72924070e90e78e94ba27ac0816f1 copied the documentation from git into the project, but the overall project license is still listed as MIT. (And in any case, you don't want to have to keep updating them from git.git.)

**Comment by Byron** [comment]
Thanks for the reminder, I agree it's time to let them go and just read it from the git repo itself :D.
