### ISSUE TITLE
Could we get a new release with the empty tag fix?

### ISSUE THREAD

**Issue by pierrechevalier83** [Byron/gitoxide#619]
### Summary 💡

Hi @Byron, thanks for your pro-activeness with reviewing and merging this PR last week: https://github.com/Byron/gitoxide/pull/604.

By any chance, would it be possible to cut a new release from any point in `main` after it was merged?

### Motivation 🔦

That would help me as I depend on `git-object` and a few other `gitoxide` crates for my work at Meta and I need to integrate that fix.

It's not urgent as we have a process for patching upstream code, but it would allow me to get back to "pure upstream" sooner rather than later, which would be nice to have.

If it's no that easy, can you explain the general release process so I can have an idea what to expect?

**Comment by Byron** [comment]
What a lucky coincidence! In the past days so many improvements were merged that I planned to cut a new release today, which should include binaries for the first time (_in a long time_) as well.

It's exciting to see Meta picked up `gitoxide`. Did you know that I plan to make it the best tool for monorepos in terms of out-of-the-box performance? Despite being set in my priorities for the coming months it will be good to know which features you would prioritize as part of your [oxidization efforts](https://github.com/Byron/gitoxide/projects/1#column-14882365) for tooling in can you can share.

I will let you know here once the release is available here.

**Comment by pierrechevalier83** [comment]
> I planned to cut a new release today, [...] I will let you know here once the release is available here.
Awesome! Thanks so much :)

> It's exciting to see Meta picked up gitoxide.
We've been using it for a little while actually. I only joined the team in the last few months, but the team had already been using `gitoxide` as a library to import `git` repos into `mononoke`, our version control backend service.

> Did you know that I plan to make it the best tool for monorepos in terms of out-of-the-box performance?
That sounds exciting :)

> Despite being set in my priorities for the coming months it will be good to know which features you would prioritize as part of your oxidization efforts for tooling.
I don't have any specific request right now as `gitoxide` seems to be meeting all of our needs for our current usage, but I will be more than happy to discuss and collaborate if and when any new need pops up.

Also, will be more than happy to contribute for any issue that shows up in our large-ish scale usecases going forward.

**Comment by Byron** [comment]
A new release of [`git-repository`](https://github.com/Byron/gitoxide/releases/tag/git-repository-v0.29.0
) and the [`gitoxide binaries`](https://github.com/Byron/gitoxide/releases/tag/v0.19.0) is now available 🎉.
