### ISSUE TITLE
Bad port '=777'

### ISSUE THREAD

**Issue by GreeFine** [Byron/gitoxide#642]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When using a repository with a custom port 777, gix fails with the message:

`Bad port '=777'`

### Expected behavior 🤔

I expect to not fail

### Steps to reproduce 🕹

1. cd into or create a git repository with a custom port
    for example: `ssh://git@lab.something.io:777/something/api.git`
2. `gix remote refs`

**Comment by GreeFine** [comment]
I have done my investigation :mag: 

And I think I found the issue:
In git-transport/src/client/blocking_io/ssh.rs

The connect function does this to specify a custom port
```rs
                if let Some(port) = port {
                    args.push(format!("-p={}", port).into());
                }
```

And when trying with ssh in my shell I get the same error
```bash
> ssh git@lab.something.io -p=777
Bad port '=777'
```

Note it work if we remove the `=`
```
ssh git@lab.something.io -p777
ssh: Could not resolve hostname lab.something.io: Name or service not known
```

**Comment by Byron** [comment]
Thanks so much! Yes, a PR is greatly appreciated and I'd love you to become a contributor :) 🙏.
