### ISSUE TITLE
Don't use bash in scripted_fixture_repo_read_only (or specify it as a dependency)

### ISSUE THREAD

**Issue by ptrcnull** [Byron/gitoxide#650]
### Summary 💡

The function documentation doesn't mention `bash` being required - it just says "Run the executable at script_name"

(on a separate note, not all executables are bash scripts? or even shell scripts at all)

### Motivation 🔦

i'm not really sure what to put here, as it's technically not a feature... but not a bug either :confused:

**Comment by Byron** [comment]
Thanks for making me aware, a very valid point about which I was a little surprised as well.

I have updated the documentation and method names to better match the status quo.

Talking about possible enhancements, what I'd love to see to make this crate more general is to execute executables for free choice of shells or tooling. I wonder what would happen if all scripts were made executable, and we try to execute them on windows where this has to work as well.

Please let me know what you think is this is a direction you like to see explored, or close the issue if the documentation fix is good enough. Thanks.

**Comment by ptrcnull** [comment]
thanks for the quick update!

in my opinion, having the option to execute any kind of.. executable would be beneficial - this way, if someone wants to create a git repo with a python script or even build their own project and use it to test itself (for example, an alternative `git` implementation in Rust could use something along the lines of `scripted_fixture_read_only("git", vec!["init"]);` in its tests)

currently, this could be a breaking change - for example, [some projects][1] don't mark their fixture scripts as executable, so running them would fail with `ENOPERM` or something similar

**Comment by Byron** [comment]
> currently, this could be a breaking change - for example, [some projects](https://github.com/o2sh/onefetch/blob/main/tests/fixtures/basic_repo.sh) don't mark their fixture scripts as executable, so running them would fail with ENOPERM or something similar

This gives me an idea! One can try to execute the file and watch for specific errors that indicate we better retry with a specific shell like `bash`. I don't think it will make a difference in code-execution speed as these scripts run only once anyway, for the most part.

**Comment by ptrcnull** [comment]
that sounds like a perfect solution, thanks :)
