### ISSUE TITLE
error: failed to select a version for `libc`

### ISSUE THREAD

**Issue by paulyoung** [Byron/gitoxide#653]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I upgraded to 94750e15831969059551af35d31c21009462084d because I wanted to use `git-repository` with `reqwest` and I thought it had landed in #648 (it actually landed in #620)

When I tried to build, I ran into this:

```
    Updating crates.io index
error: failed to select a version for `libc`.
    ... required by package `nix v0.26.1`
    ... which satisfies dependency `nix = "^0.26.1"` of package `git-prompt v0.2.0 (https://github.com/Byron/gitoxide?rev=94750e15831969059551af35d31c21009462084d#94750e15)`
    ... which satisfies git dependency `git-prompt` of package `git-credentials v0.7.0 (https://github.com/Byron/gitoxide?rev=94750e15831969059551af35d31c21009462084d#94750e15)`
    ... which satisfies git dependency `git-credentials` of package `git-protocol v0.24.0 (https://github.com/Byron/gitoxide?rev=94750e15831969059551af35d31c21009462084d#94750e15)`
    ... which satisfies git dependency `git-protocol` of package `git-repository v0.29.0 (https://github.com/Byron/gitoxide?rev=94750e15831969059551af35d31c21009462084d#94750e15)`
```
```
versions that meet the requirements `^0.2.137` are: 0.2.138, 0.2.137

all possible versions conflict with previously selected packages.

  previously selected package `libc v0.2.133`
    ... which satisfies dependency `libc = "^0.2.77"` (locked to 0.2.133) of package `async-io v1.10.0`
    ... which satisfies dependency `async-io = "^1.2"` (locked to 1.10.0) of package `async-global-executor v2.3.1`
    ... which satisfies dependency `async-global-executor = "^2.0.0"` (locked to 2.3.1) of package `async-std v1.12.0`
    ... which satisfies dependency `async-std = "^1.12.0"` (locked to 1.12.0) of package `git-repository v0.29.0 (https://github.com/Byron/gitoxide?rev=94750e15831969059551af35d31c21009462084d#94750e15)`
```

I'm guessing this is related to #647 but it's unclear what I need to do to resolve this, or if it's something gitoxide needs to fix.

### Expected behavior 🤔

A compatible version of `libc` can be found.

### Steps to reproduce 🕹

I'm not entirely sure yet but I wanted to at least file something. I'm seeing this when depending on `git-repository/async-network-client`.

**Comment by Byron** [comment]
I tried to reproduce this issue with `cd git-repository && cargo tree -i libc --features async-network-client`, but it consistently manages to resolve it to 0.2.137. Since the error messages say it's locked to `0.2.133` I wonder if `cargo update` does anything for you? If not it might be an issue with other dependencies from your tree somehow locking `libc` to an older version, which would be impossible to fix here.

Cargo is so great the in the rare cases when I see such a message I am more confused than anything else. After running `cargo update` myself it now resolves to `libc v0.2.138`, so it seems fine still on my end.

**Comment by paulyoung** [comment]
`cargo update` seems to have done the trick.

I was quite confused because I'm not depending on anything other than `git-repository` that would affect the version of `libc` required, and the output I shared previously suggested that the problem originated there.

**Comment by Jungle430** [comment]
I agree with **paulyoung's** answer upstairs,today I found the same problem,Upgrading the msvc version on windows11 has no effect,but using commanding `cargo update`, the problem is solved!
