### ISSUE TITLE
Oxidize NoseyParker

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#654]
### Required Features

_(among others that are already implemented)_

* [x] a fast way to get the size and kind of an object by ID, by reading only headers, similar to [`read_header()`](https://docs.rs/git2/latest/git2/struct.Odb.html#method.read_header).
* [x] Something like `NO_DOT_GIT` option to prevent trying two directories if one is given. (#667)
* ~~a filter to only traverse packed objects if they match a given filter to allow blob-only traversal. (for max performance)~~
* ~~Generalize [`git_odb::Store::verify_integrity()`](https://github.com/Byron/gitoxide/blob/c8835c6edae784c9ffcb69a674c0a6545dbb2af3/git-odb/src/store_impls/dynamic/verify.rs#L91-L101) so that users can be called on each decoded object to perform their own computation.~~ Not needed, possibly not actually faster.

The first [integration PR in the repository](https://github.com/praetorian-inc/noseyparker/pull/2) and [the follow-up](https://github.com/praetorian-inc/noseyparker/pull/20).

**Comment by bradlarsen** [comment]
> a filter to only traverse packed objects if they match a given filter to allow blob-only traversal. (for max performance)

This functionality would be generally useful. But in the case of Nosey Parker, though it might speed things up a bit at present, it's a low priority wish list item.

In the longer term, Nosey Parker will also be looking at tree and commit objects to gather precise metadata about blobs with matches (pathnames and the set of commits that first introduced the matching content: https://github.com/praetorian-inc/noseyparker/issues/16. To implement that, in addition to reading every blob, Nosey Parker will also have to read every commit and tree. So at that point, having a gitoxide object filter mechanism would be less useful.

**Comment by Byron** [comment]
Thanks for letting me know! I think it's best to remove it as a feature requirement alltogether, because even if you'd not be interested in, say, annotated tags, it would make no difference in performance to skip them after they have been decoded, rather than before.

The equivalent to `NO_DOT_GIT` will land in a moment by the way. Now opening repos is a bit faster as it actually does less IO in the typical case, for typically named repositories, so it's a super nice feature to have.

**Comment by Byron** [comment]
Awesome, I think everything is done as the last outstanding feature was just merged into `main`. By the time the new integration branch is ready for merge, I can cut a new release in case you'd like to use that feature and remove the workaround (it's in [ca84c87](https://github.com/Byron/gitoxide/commit/ca84c87734804cbfc65e311b89ff6ccfc236149c)).

**Comment by Byron** [comment]
I think this task is completed :).

**Comment by bradlarsen** [comment]
Yes. Thank you for your help!On Sep 4, 2023, at 03:13, Sebastian Thiel ***@***.***> wrote:﻿
I think this task is completed :).
