### ISSUE TITLE
Reading a git_pack::data::File from memory

### ISSUE THREAD

**Issue by kpcyrd** [Byron/gitoxide#658]
### Summary 💡

It woudl be cool if I could create a git_pack::data::File from a `&[u8]` that I already have in memory. :)

### Motivation 🔦

I have the data of a git pack data object in memory and don't want to write it to disk first.

**Comment by Byron** [comment]
To support that, there needs to be some abstraction in `git-pack::File` which is currently using a Memmap explicitly. As an intermediate step, I can imagine creating such `File` from an already opened memmap. That way you could create [an anonymous memmap](https://docs.rs/memmap2/0.5.8/memmap2/struct.MmapMut.html#method.map_anon) and copy the data you already have in memory into it. Despite the extra copy operation, that data is typically never going to touch disk.

An abstraction is likely to happen once WASM support is on the list of things todo, and the suggested change is something you are welcome to contribute if it would help in the case mentioned here.
