### ISSUE TITLE
Docs mention sync::Handle, but there is no such thing

### ISSUE THREAD

**Issue by jgarvin** [Byron/gitoxide#668]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

> As a shared buffer is written to back the object data, the returned ObjectRef will prevent other find_object() operations from succeeding while alive. To bypass this limit, clone this `sync::Handle` instance.

This appears in a few places in the docs, and it's confusing because:

1. It says "clone *this*" which I would expect to see on the docs for a method for the `sync::Handle`, or for it to appear in the signature of the function being documented, but neither is true. It's unclear what "this" refers to.
2. There is no `sync::Handle`. There is `OdbHandle`, maybe that's related?

My guess is the docs are out of date.

### Expected behavior 🤔

References to types that exist :)

### Steps to reproduce 🕹

1. Read docs :)

**Comment by Byron** [comment]
Thanks a lot for pointing this out. Indeed, these portions have been long forgotten and no such limitation exists anymore. 

Large portions of the `git-repository` docs have also been removed for similar reasons.

If you keep reading, please feel free to keep informing me about issues as they pop up.
