### ISSUE TITLE
Getting diff for very first commit?

### ISSUE THREAD

**Issue by jgarvin** [Byron/gitoxide#676]
### Summary 💡

AFAICT from reading docs, the way to get the changes associated with a commit is to diff a commit's tree against it parent's tree with [`for_each_to_obtain_tree`](https://docs.rs/git-repository/latest/git_repository/object/tree/diff/struct.Platform.html#method.for_each_to_obtain_tree). However, the very first commit in a repository has no parent.  At least this was the behavior I observed with the `git2` code I'm currently porting to `git_repository`. [In `git2` diff_tree_to_tree takes `Option<&Tree>` to handle this case.](https://docs.rs/git2/latest/git2/struct.Repository.html#method.diff_tree_to_tree) Is there a way to do this with `git_repository`? If not it seems like an API-hole, if so it might be helpful to have a note explaining what to do for people transitioning from `git2` :grin: 

In the `git2` version of the code I used this iterator:

```
/// Iterator adapter. Takes an iterator yielding `T` and transforms it
/// to yield `Option<T>`. If the underlying iterator has no data, then
/// the adaptor will yield `None` exactly once. If the underlying
/// iterator does have data, then the adaptor will yield `Some(x)` for
/// all x in the underlying.
fn at_least_once<I: Iterator>(mut it: I) -> impl Iterator<Item = Option<I::Item>> {
    let mut polled = false;
    std::iter::from_fn(move || {
        if !polled {
            polled = true;
            Some(it.next())
        } else {
            it.next().map(Some)
        }
    })
}
```

And then I would iterate over parents to do diffs:

```
    for parent in at_least_once(commit.parents()) {
        let diff = diff_commits(&local.repo, parent.as_ref(), &commit)?;
        // ...
    }
```

And `diff_commits` would hand the optional to `diff_tree_to_tree`, which would then do the right thing whether or not there was a parent.

### Motivation 🔦

I'm trying to search for all commits that add files that meet a certain criteria. Ideally this would work correctly even if files meeting the criteria were added in the very first commit.

**Comment by Byron** [comment]
Thanks a lot for letting me know and sorry for the hassle.

Sometimes the docs aren't up to the tasks yet, but I consider every issue like these a bug that needs immediate fixing, please see 9fabfc500 for the change.

In short, `repo.empty_tree()` can be used to create an empty tree for the cases where there is no tree to compare to.
