### ISSUE TITLE
RFC2822 and DEFAULT date friction

### ISSUE THREAD

**Issue by jpgrayson** [Byron/gitoxide#679]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

The git-date crate defines several well-known formats, including `git_date::time::format:RFC2822` and `git_date::time::format::DEFAULT`. These format descriptions are used both to parse and format `git_date::Time` objects. The problem is with the treatment of the day of month and specifically what happens with single-digit days of the month.

In the format descriptions, `[day]` is used. This is equivalent to `[day padding:zero]` ([reference](https://time-rs.github.io/book/api/format-description.html)).

When formatting, a zero-padded output is produced, e.g. `Sun, 01 Jan 2023 12:34:56 -0300` for `RFC2822` and `Sun Jan 01 12:34:56 -0300`.

### First problem

This is inconsistent with how `git` produces rfc2822 dates. For example, from a gitoxide repo:

```console
$ git log -n1 --pretty=%aD 21482848
Fri, 9 Dec 2022 19:31:38 -0600
#    ^-- single digit
```

So while [RFC 2822 itself](https://www.rfc-editor.org/rfc/rfc2822#section-3.3) calls for a "2DIGIT" day, `git` outputs a single digit when day-of-month < 10. Thus gitoxide will produce different rfc2822 date strings than `git` when using `git_date::time::format::RFC2822`.

### Second problem

When parsing dates, `git_date::time::format::RFC2822` rigidly _requires_ a two-digit day of month. Thus gitoxide will not parse rfc2822 dates originating from various `git` outputs. 

### Third problem

gitoxide's `git_date::time::format::DEFAULT` format is different than `git`'s default date output. E.g.:

`Fri Dec 09 2022 19:31:38 -0600`
vs.
`Fri Dec 9 19:31:38 2022 -0600`

I.e. the time and year components are swapped along with `git` using a non-padded day-of-month and gitoxide using a zero-padded day-of-month.

While the ordering of `git`'s default date is...unique, it is also ubiquitous. So it is a problem that `git_date::parse()` will not parse the most common date format output by `git`.

### Problem 1

It is not obvious whether gitoxide should output the same non-padded day of month that `git` outputs since `git` may not be 100% compliant with RFC 2822. Nonetheless it is somewhat surprising that gitoxide's rfc2822 output differs from `git`. This could be resolved by offering an alternative format description, e.g. `GIT_RFC2822` that produces the non-padded day-of-month like `git`.

```rust
/// E.g. `Thu, 8 Aug 2022 12:45:06 +0800`. This is output by `git log --pretty=%aD`.
pub const GIT_RFC2822: &[FormatItem<'_>] = format_description!(
    "[weekday repr:short], \
     [day padding:none] \
     [month repr:short] \
     [year] \
     [hour]:[minute]:[second] \
     [offset_hour sign:mandatory][offset_minute]"
);
```

### Problem 2

gitoxide should be able to parse rfc2822-like dates with any of:
* zero-padded day of month (e.g. `06`)
* space-padded day of month (e.g. ` 6`)
* non-padded day of month (e.g. `6`)

The `time` crate has its own `time::format_description::well_known::Rfc2822` struct which **is** able to parse all of the above day of month formats. A possible path forward would be for `git_date::parse()` to use `time::format_description::well_known::Rfc2822` instead of `git_date::time::format::RFC2822`. This, I believe, would completely solve the parsing issue.

### Problem 3

gitoxide should be able to parse `git`'s default date format, even if gitoxide uses a different default date format.

gitoxide should also provide a format description that produces `git`'s default date format. And attempt to parse with it in `git_date::parse()`. E.g.:

```rust
/// E.g. `Thu Sep 4 10:45:06 2022 -0400`. This is output by `git log --pretty=%ad`.
pub const GIT_DEFAULT: &[FormatItem<'_>] = format_description!(
    "[weekday repr:short] \
     [month repr:short] \
     [day padding:none] \
     [hour]:[minute]:[second] \
     [year] \
     [offset_hour sign:mandatory][offset_minute]"
);
```

### Steps to reproduce 🕹

```rust
#[test]
fn rfc2822_problems() {
    use git_date::time::format::RFC2822 as git_date_rfc2822;
    use time::format_description::well_known::Rfc2822 as time_rfc2822;

    let zero_padded = "Sun, 01 Jan 2023 09:32:07 -0500";
    let non_padded = "Sun, 1 Jan 2023 09:32:07 -0500";
    let space_padded = "Sun,  1 Jan 2023 09:32:07 -0500";

    let golden = time::OffsetDateTime::parse(zero_padded, &time_rfc2822).unwrap();
    assert_eq!(
        golden,
        time::OffsetDateTime::parse(non_padded, &time_rfc2822).unwrap()
    );
    assert_eq!(
        golden,
        time::OffsetDateTime::parse(space_padded, &time_rfc2822).unwrap()
    );

    assert_eq!(
        golden,
        time::OffsetDateTime::parse(zero_padded, git_date_rfc2822).unwrap()
    );

    // BUG: Fails
    assert_eq!(
        golden,
        time::OffsetDateTime::parse(non_padded, git_date_rfc2822).unwrap()
    );

    // BUG: Fails
    assert_eq!(
        golden,
        time::OffsetDateTime::parse(space_padded, git_date_rfc2822).unwrap()
    );
}

```

**Comment by Byron** [comment]
Thanks so much for investigating this! `git-date` hasn't received a lot of attention from me, and it's pleasant to see that the community picks it up to make the necessary improvements.

As much as I appreciate such a well-crafted issue that is an example for them all as well as for myself, I also see how much time it might take to produce it. There is no requirement to make issues this awesome, and if you want please feel free to submit the PR right away in future. If that saves you any time, I would be happy.

Closing since the related PR was merged as is.
