### ISSUE TITLE
ux: clone: make `<DIRECTORY>` optional

### ISSUE THREAD

**Issue by Dentrax** [Byron/gitoxide#683]
### Summary 💡

`clone` command requires `<DIRECTORY>` argument, which I think it should be optional instead: `[<DIRECTORY>]`:

git way:
```
git clone [OPTIONS] <repository> [<directory>]
```

gix way:
```
gix clone [OPTIONS] <REMOTE> <DIRECTORY>
```

### Motivation 🔦

`git` by default uses the project name when creating folders. Whereas `gix`, we have to pass manually, which makes the UX a bit slower. (since we have to copy-paste the repository name)

The following command should just work:
```bash
$ gix clone git@github.com:Byron/gitoxide.git
error: The following required arguments were not provided:
    <DIRECTORY>
```

We can easily get the `<DIRECTORY>` from the repository name, which is `gitoxide` in this case.

**Comment by Byron** [comment]
Thanks for bringing it up. As `gix` is a development tool best `ux` isn't one of its goals - that is only true for `ein` which is incumbent at best. 

That said, as it's easy enough to implement this _well enough_, I have implemented it now. Please note that `git` applies more logic than is currently implemented so the results may differ in some less common cases. Also, I fixed a bug that would make it possible to deadlock clones with `ssh` urls, thus you might want to build a fresh `gix` from `main`.

**Comment by Dentrax** [comment]
Wow, thanks for such prompt action!
