### ISSUE TITLE
Shallow clone

### ISSUE THREAD

**Issue by yonas** [Byron/gitoxide#686]
### Summary 💡

The only thing holding me back from using gitoxide is shallow clones. Implement it.

### Motivation 🔦

Often, I don't want all the commits, just the last one.

**Comment by Byron** [comment]
It's already on the roadmap and you can [follow this tracking issue](https://github.com/Byron/gitoxide/issues/450) for more, or watch new releases of the `gitoxide` project.
Thanks for your understanding.
