### ISSUE TITLE
[smart-release] Use sentence case when rendering conventional commit messages.

### ISSUE THREAD

**Issue by zicklag** [Byron/gitoxide#693]
### Summary 💡

When rendering the commit messages in the changelog, it should capitalize the first letter of the conventional commit title.

### Motivation 🔦

A common ( or at least default in commitlint ) commit lint dictate that the commit message start with a lowercase letter, but in a changelog it's more appropriate I believe to capitalize the first letter of the commit message.

Would you be open to a PR that updates this?

**Comment by Byron** [comment]
That's a great idea and I would appreciate a PR for that.

**Comment by ryand67** [comment]
@Byron I'd love to take a shot at this as a new contributor :)

**Comment by rosefromthedead** [comment]
Pinging because I think this issue can be closed?
