### ISSUE TITLE
git-url parsing

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#7]
In the git-url crate, implement parsing of all URL types that git supports, as documented here: https://www.git-scm.com/docs/git-clone#_git_urls 

The implementation should be practical, and does require tests for each case.

`nom` can be used, and if used, the parser should _not_ support streaming.
Please feel free to add your author name into the crate list.

It's preferred to have a WIP PR and push all results into that one as I must reserve the right to pick up what's there in case development stalls to avoid blocking overall progress.

**Comment by bluejekyll** [comment]
I believe that the [url](https://crates.io/crates/url) crate will support all of the features necessary. Any reason you see as not using that?

**Comment by Byron** [comment]
Great point, I think it could do some of the parsing, and avoid common pitfalls around URLs. Some Git-URLs are shortened forms of URLs that probably won't parse unless they are cononicalized, which is probably why I thought about custom parsing.
Besides, I am quite avoidant to pulling in new crates to keep compile times at bay.

That said, I realize that this issue was created in a rush and doesn't match the quality standards I aim to uphold for this project, which is why I like to take a step back and close it in favor of getting #8 done first.

Thanks for your understanding
