### ISSUE TITLE
Panic on arm64v8

### ISSUE THREAD

**Issue by oknozor** [Byron/gitoxide#702]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Calling the following function: https://github.com/oknozor/gill/blob/main/crates/gill-git/src/clone.rs#L7-L58
Produce the following error when running on target `aarch64-unknown-linux` : 
```
gill  | 2023-01-29T15:24:07.977401Z DEBUG request{method=GET uri=/oknozor/gill/pulls/14/merge version=HTTP/1.0}: tower_http::trace::on_request: started processing request
gill  | thread 'gitoxide.in_parallel.produce.3' panicked at 'not yet implemented', /cargo/registry/src/github.com-1ecc6299db9ec823/git-worktree-0.11.0/src/index/entry.rs:101:43
gill  | thread 'main' panicked at 'no panic: Any { .. }', /cargo/registry/src/github.com-1ecc6299db9ec823/git-features-0.26.1/src/parallel/in_parallel.rs:98:6
```
https://github.com/Byron/gitoxide/blob/f4bc31e69bf7d6f5245d4070058176ae6263be03/git-worktree/src/index/entry.rs#L101
https://github.com/Byron/gitoxide/blob/f4bc31e69bf7d6f5245d4070058176ae6263be03/git-features/src/parallel/in_parallel.rs#L98

This does not happen on a amd64 host. 

### Expected behavior 🤔

Should work the same regardless of the architecture.

### Steps to reproduce 🕹

This is a bit hard to reproduce, because it requires getting your hand on an arm machine or doing a complex cross setup (git is needed inside the host container). 

I'll work on a reproducer later if needed.

**Comment by oknozor** [comment]
Actually after testing this again it seems it's not related at all to the target architecture. I was missleaded by the conditional compilations attributes on the `checkout` function. 

I guess this is due to the target repository containing a submodule.
Sorry for the noise.

**Comment by Byron** [comment]
No worries! Yes, indeed it's not quite ready for primetime yet even though many repos work, those who don't panic.
