### ISSUE TITLE
OSS-fuzz: Code coverage failure

### ISSUE THREAD

**Issue by silvergasp** [Byron/gitoxide#719]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

NOTE: This problem was origionally mentioned here https://github.com/Byron/gitoxide/pull/714#issuecomment-1416795136.

Currently oss-fuzz is failing to generate code coverage for gitoxide. This is likely due to the missing component rust-src not being added to the Docker container.

### Expected behavior 🤔

Code coverage reports should be generated from OSS-fuzz.

### Steps to reproduce 🕹

See https://github.com/Byron/gitoxide/pull/714#issuecomment-1416795136 for logs.

**Comment by silvergasp** [comment]
@Byron I've added myself to the ['auto_ccs' in the project.yml](https://github.com/google/oss-fuzz/pull/9581/files#diff-b2f9e2a45a8860371f5d296e503d41f7bb105fbdb8b937d7376fb0bd7d545750R4-R5) for the OSS-fuzz project. This means I will get read-only access to the dashboard for gitoxide. Hopefully, this will help me debug any future problems and I'll be able to help deal with bugs. I'd like to get the Ok from you before adding myself to this list (the PR needs to be merged before I get access). Is this something that you are comfortable with?

**Comment by Byron** [comment]
Thanks for taking the lead on this, it's much appreciated.

**Comment by Byron** [comment]
I just got a message that the coverage report is still failing.

```
Step #5: [2023-02-09 06:05:07,402 INFO] Finished finding shared libraries for targets.
Step #5: [0;31merror: /workspace/out/libfuzzer-coverage-x86_64/rustc/ef934d9b632b8ac00276558824664c104b92b5f0/library/std/src/thread/local.rs: No such file or directory
Step #5: [0m[0;31mwarning: The file '/rustc/ef934d9b632b8ac00276558824664c104b92b5f0/library/std/src/thread/local.rs' isn't covered.
Step #5: [0m[2023-02-09 06:05:07,935 DEBUG] Finished generating per-file code coverage summary.
Step #5: [2023-02-09 06:05:07,935 DEBUG] Generating file view html index file as: "/workspace/out/libfuzzer-coverage-x86_64/report/linux/file_view_index.html".
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 577, in PrepareHtmlReport
Step #5:     self.GenerateFileViewHtmlIndexFile(per_file_coverage_summary,
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
Step #5:     self.GetCoverageHtmlReportPathForFile(file_path),
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 422, in GetCoverageHtmlReportPathForFile
Step #5:     assert os.path.isfile(
Step #5: AssertionError: "/rustc/ef934d9b632b8ac00276558824664c104b92b5f0/library/std/src/thread/local.rs" is not a file.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image gitoxide
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage gitoxide
Step #5: python infra/helper.py coverage gitoxide
Step #5: ********************************************************************************
Finished Step #5
```

I checked and the `rust-src` component is indeed present now.

**Comment by silvergasp** [comment]
So I just did a bit of a deeper dive and it looks like we need to merge each sub-crate fuzzer into a root level fuzz directory similar to the [wasmtime](https://github.com/bytecodealliance/wasmtime/tree/main/fuzz) repository. There have been similar issues;
- https://github.com/google/oss-fuzz/issues/5767
- https://github.com/google/oss-fuzz/issues/5341

I'll investigate further and get back to you. Apologies for not double-checking my fix :)

**Comment by silvergasp** [comment]
> **Maybe coverage can be disabled?** After all, there isn't any expectation the coverage is great, it's mainly for parsers right now and we naturally improve coverage over time without this being a metric.

If it is possible I don't know where it's documented...

**Comment by silvergasp** [comment]
I've got a couple more integration tests to run to ensure that this is going to work, but I've got a draft PR here that I'm hoping will fix the issue https://github.com/Byron/gitoxide/pull/727

**Comment by silvergasp** [comment]
#727 was a non-starter. I've opened an issue upstream https://github.com/google/oss-fuzz/issues/9677

**Comment by Byron** [comment]
Thanks a lot for your help, it's much appreciated.
