### ISSUE TITLE
Unable to handle ssh host aliases

### ISSUE THREAD

**Issue by jalil-salame** [Byron/gitoxide#725]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I used the Arch Linux package `gitoxide 0.20.0-2` 

```console
$ gix --version
gix-plumbing 0.20.0
```

I happen to have two GitHub accounts and I use ssh Host aliases to manage the ssh keys:

```ssh-config
Host github.com
    IdentityFile ~/id_1

Host PersonalGH
    HostName github.com
    IdentityFIle ~/id_2
```

This fails for me:

```console
$ gix clone "git@PersonalGH:jalil-salame/dooit-rs.git" test
Error: Could not verify that "/home/jalil/Programming/Personal/git@PersonalGH:jalil-salame/dooit-rs.git" url is a valid git directory before attempting to use it

Caused by:
    0: Could not retrieve metadata of "/home/jalil/Programming/Personal/git@PersonalGH:jalil-salame/dooit-rs.git/.git"
    1: No such file or directory (os error 2)
```

### Expected behavior 🤔

Successful clone of the repository (or error on `ssh host aliases not supported`)

### Steps to reproduce 🕹

1. Add a host alias to your ssh config:

    ```ssh-config
    Host Test
        HostName github.com
    ```

3. Try to clone from that alias (`gix clone git@Test:Bryon/gitoxide.git`)
4. See the error message

**Comment by Byron** [comment]
Can you try to compile from the main branch and validate the issue persists?
It’s unclear which version you are using and there have been fixes that may affect this issue.

In theory, as we shell out the transport to “ssh” it should work just like it does for git.

**Comment by jalil-salame** [comment]
I updated the report to include the `gitoxide` version and installation source, I am currently compiling `main` in my laptop, please send help (or a few extra cores).

**Comment by jalil-salame** [comment]
For commit `a3df7b5e3`, the error message stays the same (compiled with `cargo build --release --no-default-features --features lean`).

I don't think this is a issue with delegating to `ssh`, I think `gix` fails to identify this url as an ssh url and tries to interpret it as a path to disk.

**Comment by Byron** [comment]
Thanks for validating this! Indeed, it fails because it considers the URL a file instead of ssh and consequently won't even try to start `ssh` as transport.

This particular case is now fixed.

I wonder if `alias:path.git` is also a valid `scp` like URL, because that is still considered a file path rather than ssh even in the current implementation.

**Comment by Byron** [comment]
Can you retry in `main`? It should work now. Thanks.
