### ISSUE TITLE
Consider using faster DEFLATE implementations

### ISSUE THREAD

**Issue by Shnatsel** [Byron/gitoxide#732]
### Summary 💡

[`zune-inflate`](https://crates.io/crates/zune-inflate) is a translation of [libdeflate](https://github.com/ebiggers/libdeflate) to safe Rust. So far it only implements decompression, but should be noticeably faster than `miniz_oxide` used in gitoxide currently, and is roughly on par with `zlib-ng` for decompression. The catch is that it doesn't support streaming, so I'm not sure if this will be applicable.

Besides that, I'm not sure if this is relevant since gitoxide is already multi-threaded, but the [`gzp`](https://crates.io/crates/gzp) crate implements parallel DEFLATE compression on top of a configurable backend, and is implemented in safe Rust.

### Motivation 🔦

Performance go brrrrrr

**Comment by Byron** [comment]
Thanks for the hint!

Before it can be tested, streaming would need to be supported. Maybe that's something we can link to from here once it's accepted as issue in the `zune-inflate` project.

Something I am particularly interested in is to see the 'millions-of-zlib-streams' performance then, which is just as important as raw inflate performance when it comes to decoding packs.

**Comment by Shnatsel** [comment]
Streaming is not currently on the roadmap, and is unlikely to be supported in the near future.

If the pack compression is already multi-threaded, then there will be no benefit from using `gzp` either and this issue can be closed.

**Comment by Byron** [comment]
Thanks for the update! I agree that it's not worth keeping this issue open then, and maybe one day `zune-inflate` will be eligible and we can try again here.
