### ISSUE TITLE
Rename of git-repository to gix breaks cargo doc

### ISSUE THREAD

**Issue by Osse** [Byron/gitoxide#736]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Running `cargo doc` issues a warning:

    warning: output filename collision.
    The lib target `gix` in package `gix v0.35.0 (/home/osse/dev/gitoxide/gix)` has the same output filename as the bin target `gix` in package `gitoxide v0.22.0 (/home/osse/dev/gitoxide)`.
    Colliding filename is: /home/osse/dev/gitoxide/target/doc/gix/index.html
    The targets should have unique names.
    This is a known bug where multiple crates with the same name use
    the same path; see <https://github.com/rust-lang/cargo/issues/6313>.

The resulting documentation for the `gix` crate is that of the binary, which isn't all that interesting.

### Expected behavior 🤔

What I _want_ to happen is to see the documentation for the crate that used to be named `git_repository`. But given that `cargo doc` prints that warning I'm not sure what I _expect_ anymore 😛 A workaround is to run `cargo doc -p gix`.

### Steps to reproduce 🕹

Run `cargo doc` from the top-level of the repository and open `target/doc/gix/index.html` in your preferred browser. See the docs for the `gix` binary instead of the crate.

**Comment by Osse** [comment]
I noticed just now that the docs on docs.rs are correct... Given that there's a limitation in `cargo doc` itself I'm fine with this being closed as a "won't fix", honestly.

**Comment by Byron** [comment]
I agree. The relationship between the crates didn't get simpler with the rename (which still isn't completed), but it's a trade worth making.

Running `cargo doc -p gix` or using docs.rs seems acceptable especially since docs of the root `gitoxide` crate isn't ever going to be that that useful due to its nature.

**Comment by Osse** [comment]
Fair. I wonder how docs.rs generates its docs in the first place.
