### ISSUE TITLE
`gix clone` requires committer info

### ISSUE THREAD

**Issue by bittrance** [Byron/gitoxide#737]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

gix requires committer info to clone.

### Expected behavior 🤔

`git clone` can operate without committer info. There will be no actual change to the reflog in the basic clone scenario.

### Steps to reproduce 🕹

```
[21:04] cargo run -- clone https://github.com/bittrance/kitops ./kitops
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/gix clone 'https://github.com/bittrance/kitops' ./kitops`
HEAD:refs/remotes/origin/HEAD (implicit)
        69ec5a78190df3ff80777e69e7189ee4be435ea0 HEAD symref-target:refs/heads/main -> refs/remotes/origin/HEAD [new]
+refs/heads/*:refs/remotes/origin/*
        69ec5a78190df3ff80777e69e7189ee4be435ea0 refs/heads/main -> refs/remotes/origin/main [new]
[21:04] mv ~/.gitconfig ~/.gitconfig.bak
[21:04] rm -rf ./kitops
[21:05] cargo run -- clone https://github.com/bittrance/kitops ./kitops
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/gix clone 'https://github.com/bittrance/kitops' ./kitops`
Error: Failed to update references to their new position to match their remote locations

Caused by:
    0: The reflog could not be created or updated
    1: reflog messages need a committer which isn't set
```
Removed perf info for brevity.

**Comment by Byron** [comment]
Thanks for reporting.

Could you show the reflog on `main` after cloning with `git` while no committer information is present? I'd be interested in learning what `git` fills in there.

That said, the reflog needs a committer and `gitoxide` stopped to fill it automatically. It should also work like `git` by default where it makes sense. Here it seems innocent enough to do that as well as most people won't find the correct committer name in reflogs too important either.

Thanks for your help.

**Comment by bittrance** [comment]
Hm, inspired:
```
commit 69ec5a7 (HEAD -> main, origin/main, origin/HEAD)
Reflog: HEAD@{0} (Bittrance <bittrance@bittrance.(none)>)
Reflog message: clone: from https://github.com/bittrance/kitops
```
Without checking the git sources, I'm guessing passwd comment + user name + `domainname` output.

Personally, I would have preferred "no clue" :shrug:

**Comment by Byron** [comment]
> Personally, I would have preferred "no clue" 🤷

It now defaults to something static if nothing is set instead of guessing like `git` does. In the course of this I also improved `git-config` to make certain interactions possible, so this seemingly simple fix ended up being more involved but also caused a lot of improvements under the hood. Neat! 

Thank you.
