### ISSUE TITLE
potentially useful: gix::ObjectId::empty_file(...)

### ISSUE THREAD

**Issue by asottile** [Byron/gitoxide#743]
### Summary 💡

I notice there's already a quick helper for `empty_tree` -- was wondering if one for the empty file would be useful as well

happy to submit a PR if this sounds like a good idea -- also completely fine with a "no" here -- I totally understand!

### Motivation 🔦

`git` uses this a bit internally, for instance for `--intent-to-add` (which is where I'm hitting it!)

no biggie, I can always use:

```rust
let oid = gix::ObjectId::from_hex(b"e69de29bb2d1d6434b8b29ae775ad8c2e48c5391").unwrap();
```

or whatever

**Comment by Byron** [comment]
That seems valid point and I definitely welcome a PR. The name of the function should be `empty_blob()` then. Thanks.
