### ISSUE TITLE
Having trouble compiling git-glob 0.5.4 with rustc 1.67.1

### ISSUE THREAD

**Issue by devyn** [Byron/gitoxide#747]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

rustc is giving an error about the particular `AsRef` implementation desired being unclear

```
error[E0282]: type annotations needed
   --> /home/devyn/.cargo/registry/src/github.com-1ecc6299db9ec823/git-glob-0.5.4/src/wildmatch.rs:248:62
    |
248 | ...                   let class = &pattern.as_ref()[p_idx + 2..closing_bracket_idx - 1];
    |                                            ^^^^^^
    |
help: try using a fully qualified path to specify the expected types
    |
248 |                                         let class = &<BStr as AsRef<T>>::as_ref(pattern)[p_idx + 2..closing_bracket_idx - 1]
;
    |                                                      +++++++++++++++++++++++++++       ~

For more information about this error, try `rustc --explain E0282`.
```

### Expected behavior 🤔

I'm not sure if it's something to do with the rustc version, or if something else just got changed this doesn't compile anymore, but it's surprising to me that CI would be building it just fine and yet I can't build it.

### Steps to reproduce 🕹

Trying to install the latest git version of helix editor, which indirectly depends on `git-glob`.

Rust stable toolchain 1.67.1, installed by rustup on Linux.

**Comment by Byron** [comment]
I am working on a fix already, testing and releasing will take some time, but it should be ready in about an hour, latest.

**Comment by Byron** [comment]
Here is a PR which should constitute a fix: https://github.com/helix-editor/helix/pull/6065 .

Maybe it's possible to temporarily yank the `bstr` crate to give people some time to upgrade to the latest `gix` crate.

**Comment by Byron** [comment]
Closing as this seems to be fixed now. `helix` can't update just yet though.

**Comment by FMFigueroa** [comment]
https://github.com/cargo-generate/cargo-generate/issues/879

**Comment by Byron** [comment]
https://github.com/cargo-generate/cargo-generate/pull/880 should fix it.

**Comment by danielzgtg** [comment]
Other downstream crates also affected by this include https://github.com/starship/starship and https://github.com/Canop/bacon/issues/112 .

**Comment by Byron** [comment]
Starship has the fix merged already and would need a new release, whereas `bacon` now [has a fix waiting](https://github.com/Canop/bacon/pull/113).

**Comment by jonhoo** [comment]
So this suggests there won't be a fix for this in `git-glob` then? The only fix is to move to `gix`?

**Comment by Byron** [comment]
I lost my text unfortunately, but in short I don't feel to go through the trouble of backporting a fix for an issue that seems to have a workaround, namely to use a lock file. Thanks for your understanding.

**Comment by japert** [comment]
For other readers of this thread, who have this issue but don't follow the development of gitoxide enough to understand 

>  I don't feel to go through the trouble of backporting a fix for an issue

why this required backporting a fix.

In my case, I depended on crate `git-repository`. This was renamed to `gix`. So if you change your dependencies from `git-*` to `gix-*`, it should be resolved.
