### ISSUE TITLE
Missing negtive in error message returned by 'gix::discover'

### ISSUE THREAD

**Issue by hsaunders1904** [Byron/gitoxide#771]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

The message in the error returned by `git::discover` when a directory exists, but is not part of a git repository, is missing a 'not'. The message is:

> Could find a git repository in '\<path>' or in any of its parents

### Expected behavior 🤔

The message should probably be:

> Could _not_ find a git repository in '\<path>' or in any of its parents

### Steps to reproduce 🕹

```rust
fn main() {
    let result = gix::discover("/");  // assuming your root directory is not a git repo
    println!("{}", result.unwrap_err());
}
```

Using `gix = v0.39.0`.

Looks like a simple fix, happy to open PR later today if you'd like. Thanks for the library!

**Comment by Byron** [comment]
Thank you for letting me know, and yes please, a PR would be very welcome!
