### ISSUE TITLE
Blake3 support

### ISSUE THREAD

**Issue by yonas** [Byron/gitoxide#780]
### Summary 💡

In addition to SHA3-256 (or just SHA-256), supporting Blake3 would be great.

### Motivation 🔦

Blake3 is extremely fast and secure.

![BLAKE3-benchmark](https://user-images.githubusercontent.com/110130/225387360-fa03d313-a660-49a2-9a58-65f830d3c5b3.svg)

**Comment by Byron** [comment]
Once #281 lands it should be possible to more easily plug in many other hash algorithms at hearts content. To make these useful, the `git` project would have to adopt them first and SHA256 is already kind of stalled, so I don't see any of this happening anytime soon.
