### ISSUE TITLE
`gix` ignores credential helper (macOS)

### ISSUE THREAD

**Issue by philipahlberg** [Byron/gitoxide#787]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Using the `gix` library to fetch a private repository (with the default configuration) causes a prompt for authentication (repeatedly).

### Expected behavior 🤔

Using `git fetch` does not prompt, so it presumably uses my configured credential helper (`osxkeychain`) to authenticate. 

### Steps to reproduce 🕹

1. Create a private repository.
2. `cargo init --bin`
3. `cargo add gix --features "blocking-network-client blocking-http-transport-reqwest blocking-http-transport-reqwest-rust-tls"` (adding the features for completeness, not sure if they are relevant)
4. Write the following in `src/main.rs`:

```rs
use gix::remote::Direction;

fn main() {
    let repo = gix::discover(".").unwrap();
    let outcome = repo
        .find_default_remote(Direction::Fetch)
        .unwrap()
        .unwrap()
        .connect(Direction::Fetch, gix::progress::Discard)
        .unwrap()
        .prepare_fetch(Default::default())
        .unwrap()
        .with_dry_run(true)
        .receive(&gix::interrupt::IS_INTERRUPTED)
        .unwrap();

    dbg!(&outcome);
}
```
5. `cargo run`

## Environment

OS: macOS 13.1

`git --version` prints:
```
git version 2.37.1 (Apple Git-137.1)
```

`git config credential.helper` prints:
```
osxkeychain
```

I'm presumably fetching via https when using `git`.

Please let me know if there is any more information I can provide to assist you.

**Comment by philipahlberg** [comment]
> In order to learn about the credential helper that comes with the git installation, one needs to [gix::discover(…) but with options](https://github.com/Byron/gitoxide/blob/9723e1addf52cc336d59322de039ea0537cdca36/src/plumbing/main.rs#L86) which is a little more involved.

I see - then I suppose it's not really a bug? I'll close it if that's the case.

> However, from https://github.com/Byron/gitoxide/discussions/786 it seemed like `gix fetch` also has this issue, so I assume the 'Steps to reproduce' actually involve doing `gix fetch` or `gix clone` instead.

Sorry, I wasn't clear on that part - I'm only referring to `gix` the library.

> To be sure, which protocol do you see with `git remote -v`? Which version of `gix` are you using? Is it the latest one?

For `git remote -v`, both fetch and push use `https`. But seeing as I probably misunderstood the "bug", it's likely not relevant anyway.

Thanks

**Comment by Byron** [comment]
Thank you, this clearly is a foot-gun and it wasn't documented where the issue would arise. I have updated the documentation to make the behaviour clearer.

To me this issue also exposes being between a rock and a hard place as a user shouldn't have to know that at all, as there is no way to predict what configuration will be required and whether it will be worth paying for the additional invocation of the `git` binary which in itself is a hazard that can't ever be enabled by default. Maybe in future there should at least be an alternative invocation of `gix::discover(…)` to make it easier to make this option adjustment happen.
