### ISSUE TITLE
Empty tree gives a parse error

### ISSUE THREAD

**Issue by taralx** [Byron/gitoxide#79]
Tree parsing is defined as `all_consuming(many1(parse_entry))`, which rejects the (valid) empty tree. I'm pretty sure that should be `many0`.

**Comment by Byron** [comment]
Thanks for pointing this out - I couldn't agree more! These trees seem to be a true rarity in real world repositories, but it's not a reason to fail either :).

If you feel like becoming a contributor, a PR for this would be very welcome. It should be trivial to drop down an empty file [for a test](https://github.com/Byron/gitoxide/blob/9fe139b85c350c8cbb78975a94f4548130764b1c/git-object/tests/immutable/tree.rs#L19) and see it succeed with the fix applied.
