### ISSUE TITLE
Gitoxide fails to load binary configuration on windows 11 with git 2.22

### ISSUE THREAD

**Issue by pascalkuthe** [Byron/gitoxide#790]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

First reported in https://github.com/helix-editor/helix/issues/6358

Opening a repository fails if the system git version is 2.22 on windows 11 (probably other windows versions too) when gitoxide trys to read configuration from the system git executable fails with the following error:

```
0: Failed to load the git configuration
1: Could not read configuration file
2: The filename, directory name, or volume label syntax is incorrect. (os error 123)'
```

Installing git 2.40 fixes the problem

### Expected behavior 🤔

* Properly load the configuration with git 2.22
* don't fail to open the repo because shelling out to git fails, simply log an error instead. Implementing a retry downstream would be cumbersome and necessarily slow (repo discovery would run twice). If falling is still desired by default maybe a config option could be added?

### Steps to reproduce 🕹

1. on windows install git 2.22
2. try to open a git repository with helix (https://github.com/helix-editor/helix/pull/6441) and observe the error in the cli, git integration is not working.

Failing function using gitoxide:
``` rust
fn open_repo(path: &Path, ceiling_dir: Option<&Path>) -> Result<ThreadSafeRepository> {
        let mut git_open_opts_map = gix::sec::trust::Mapping::<gix::open::Options>::default();
        let config = gix::permissions::Config {
            system: true,
            git: true,
            user: true,
            env: true,
            includes: true,
            git_binary: cfg!(windows),
        };
        git_open_opts_map.reduced = git_open_opts_map.reduced.permissions(gix::Permissions {
            config,
            ..gix::Permissions::default_for_level(gix::sec::Trust::Reduced)
        });
        git_open_opts_map.full = git_open_opts_map.full.permissions(gix::Permissions {
            config,
            ..gix::Permissions::default_for_level(gix::sec::Trust::Full)
        });
        let mut open_options = gix::discover::upwards::Options::default();
        if let Some(ceiling_dir) = ceiling_dir {
            open_options.ceiling_dirs = vec![ceiling_dir.to_owned()];
        }
        let res = ThreadSafeRepository::discover_with_environment_overrides_opts(
            path,
            open_options,
            git_open_opts_map,
        )?;
        Ok(res)
    }
```

**Comment by Byron** [comment]
Thanks a lot for letting me know!

This issue has been fixed in `gix 0.43`.
