### ISSUE TITLE
Adjust license to include Apache2 and add contribution guidelines similar to Rust-Analyzer

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#8]
Right now is not a good time to contribute as a few parts are missing:

* [x] I still want to have a dual license like many popular Rust projects do, also offering Apache 2
* [x] There should be well thought-out contribution guidelines that learn from the best, I heard Rust Analyzer is a great example

**Comment by Byron** [comment]
@joshtriplett Would you be OK to adjust your contribution to include the Apache 2 license so this project can go dual-licensed? Thanks for your consideration.

**Comment by joshtriplett** [comment]
Yes, of course. :+1:

**Comment by Byron** [comment]
We have a contribution guide and the project is dual licensed as well. It seems OK to close this one or bring up new issues otherwise.
