### ISSUE TITLE
Support equivalent of `git_revwalk_hide_cb`

### ISSUE THREAD

**Issue by vlad-ivanov-name** [Byron/gitoxide#801]
### Summary 💡

https://libgit2.org/libgit2/#HEAD/group/callback/git_revwalk_hide_cb

Related: https://github.com/rust-lang/git2-rs/issues/662

### Motivation 🔦

This would allow to hide commits and their parents during rev walk, which is useful for improving performance in certain scenarios.

**Comment by Byron** [comment]
Thanks for giving an incentive to (finally) expose this functionality in `gix` as well. I also looked at the linked git2 PR and concluded the lifetime for the pruning/hide filter is suitable.

The functionality is now available in `main`.
