### ISSUE TITLE
Support equivalent of `GIT_SORT_REVERSE | GIT_SORT_TOPOLOGICAL` in rev walk

### ISSUE THREAD

**Issue by vlad-ivanov-name** [Byron/gitoxide#807]
### Summary 💡

There's `gix_traverse::commit::Sorting::Topological`, but I haven't found a way to reverse the traversal

### Motivation 🔦

Used during filtering in https://github.com/josh-project/josh/

**Comment by Byron** [comment]
After having looked at [the source code of `libgit2`](https://github.com/libgit2/libgit2/blob/51f3e0a49b0425b59fc395349cd48f7c6abc6b83/src/libgit2/revwalk.c#L659-L669) it became clear that they aren't doing anything smart to perform this impossible feat. After all, commits are linked to their ancestors, but not to their descendants which means they do the equivalent of `id.ancestors().all().collect::<Vec<_>>().into_iter().rev()`.

As Rust has combinators for this I believe these should be used instead to not hide potentially considerable latency and memory consumption behind a seemingly innocent flag. Thanks for your understanding.

**Comment by nrdxp** [comment]
would it be possible to implement this more performantly by implementing DoubleEndedIterator for a Walk?

**Comment by nrdxp** [comment]
I believe with #1610 this would now be possible, without hurting performance, although its not for Topological searches, it is extremely fast.

**Comment by Byron** [comment]
Thanks for making this happen! I wasn't aware that simply traversing by oldest first can mean such a huge saving, and is definitely something that should be made available.
I think may also have been wrong about my initial assessment which lead to closing the issue, so reopening.
