### ISSUE TITLE
libssl1.1 is being deprecated 

### ISSUE THREAD

**Issue by TapiaX** [Byron/gitoxide#808]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

In Ubuntu 22.04 the binaries show the error `libssl.so.1.1: cannot open shared object file: No such file or directory`  this is beacuse its deprecated in favor of libssl3. After installing libssl1.1 from previous releases they run appropiately.

### Expected behavior 🤔

Both binaries must run without this error or it must be showed during installation. Maybe an upgrade on this dependency aswell, Idk where this affects.

### Steps to reproduce 🕹

1. Check that there isnt libssl1.1 installed
2. follow installation instructions via cargo

**Comment by Byron** [comment]
Thanks for letting me know! 

I have updated the installation instructions to start with the most compatible way of installation which has the greatest likelihood to work.

For completeness it's reproduced here:

```
# A certain way to install `gitoxide` with just Rust and a C compiler installed.
# If there are problems with SSL certificates during clones, try to omit `--locked`.
cargo install gitoxide --locked --no-default-features --features max-pure 

# The default installation, 'max', is the fastest, but also needs some libraries available to build successfully.
# Installing these is platform-dependent and thus can't be explained here.
cargo install gitoxide
```

For now there is no way of getting around using `libssl1.1` in the other builds as this isn't a direct dependency of `gitoxide`. Once `curl` catches up, this might change though but it's out of scope of this project to deal with that. `git` also uses `libcurl` and providing a network layer that uses it as well helps to allow `gitoxide` to be most compatible, also in regards to how (HTTP) protocol specific options are interpreted.

**Comment by kranurag78** [comment]
I faced similar issue while installing gitoxide. However the command suggested above fixed that. I was able to install and use gix afterwards. 
Can you please give me a reference on how can I install other gix components like gix-hash, gix-worktree and more?

**Comment by Byron** [comment]
That's great to hear!

> Can you please give me a reference on how can I install other gix components like gix-hash, gix-worktree and more?

`gix-*` crates aren't binaries, those are crates that are all exposed through the `gix` crate. Most folks wouldn't want to use them directly, they are plumbing for application developers, `gix` is porcelain for application developers, `gitoxide` is a collection of two binaries that ultimately use `gix` to make features available on the command-line.
