### ISSUE TITLE
gix::open() : support bare repo with index

### ISSUE THREAD

**Issue by lafleurdeboum** [Byron/gitoxide#823]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

If a bare repo has an index, opening it fails with : 
```
Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
The error message doesn't mention what file was not found, but I tracked the error down, and it appears it happens because there _is_ an `index` file in the bare repo. BTW that's apparently [legal](https://stackoverflow.com/questions/3630183/can-a-bare-repository-have-an-index-is-this-a-bug#comment131670249_3630336). It also happens when one adds eg notes to a bare remote, like when using [this laminar post-receive hook](https://github.com/ohwgiles/laminar/blob/dab620b01e0f0516e0aabb813c6357446c51e0fe/examples/git-post-receive-hook-notes#L31) ([laminar](https://laminar.ohwg.net/) is a popular lightweight CI).

### Expected behavior 🤔

Obviously, open the repository even though it has objects in its index.

### Steps to reproduce 🕹

1. `(mkdir bare_repo_with_index.git && cd bare_repo_with_index.git && git init --bare && touch index)`
2. in `main()`: `gix::open("bare_repo_with_index.git");`

See error above. The same behaviour is observed without the `.git` extension.

**Comment by Byron** [comment]
Thanks a lot for reporting! `main` will have the fix now. Please let me know if there is anything else or if it's not working for you.
