### ISSUE TITLE
Bump prodash to a version not pinned on time =0.2.22

### ISSUE THREAD

**Issue by edward-shen** [Byron/gitoxide#89]
This issue was created to track progress on `RUSTSEC-2020-0056` and `RUSTSEC-2020-0071`, which are advisories caused by a dependency on `time =0.2.22` (see time-rs/time#293 for more details).

The git-oxide project won't be affected by these advisories until [local time support is added](https://github.com/users/Byron/projects/1#card-59916208).

Requirements to close this issue:
 - [x] `prodash` dependency is bumped to a version not depending on `time =0.2.22`.
 - [x] Exceptions are removed in `deny.toml`.

**Comment by Byron** [comment]
This has been fixed in the mean time 🎉.
