### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by nu8** [Byron/gitoxide#9]
It seems this is not currently supported:

- <https://github.com/Byron/gitoxide#roadmap-to-10>
- <https://github.com/Byron/gitoxide/blob/main/tasks.md#cloning>

posting this issue in case others are interested in this like I am. Currently I
am using a custom fully static build of the C Git, but a Rust version would be
interesting.

**Comment by Byron** [comment]
Thanks for your interest, it's much appreciated! Cloning is something I am working on right now, literally :D.

Unfortunately, this issue doesn't add anything I need to keep track of, so I would like to close it. If you would like to be notified, please watch the releases of this repository - the next one, 0.4, will including basic cloning over at least one protocol.

<img width="457" alt="Screenshot 2020-08-14 at 10 32 59" src="https://user-images.githubusercontent.com/63622/90207842-deb25800-de19-11ea-90e7-43b4d656dc69.png">

Thanks for your understanding.

**Comment by nu8** [comment]
You probably have your own idea, but I would suggest cURL:

https://docs.rs/curl

I did some searching a while back, and I ended up choosing it because it had the lowest package footprint I could find

**Comment by Byron** [comment]
Thanks a lot, I will be checking it out.
It looks like `git` is also using it, so maybe it's worth making an exception to the 'Rust-only' rule. On the other hand, feature toggles might help to eventually support that along with something small and Rust-only.
Let's see.

**Comment by nu8** [comment]
You might not be interested in this either, but another approach could be to use LibGit:

https://github.com/rust-lang/git2-rs

**Comment by Byron** [comment]
That is correct, this project would defeat its purpose if (lib)git2 would be used for anything.

**Comment by nu8** [comment]
well if you must avoid LibGit, and also C, its a big task. Good luck to you!

**Comment by Byron** [comment]
Thank you! It certainly takes some. C (or `unsafe`) can't totally be avoided, but if there is a _practical_ choice, `gitoxide` will do it's best to chose to avoid both of these.

"Assume you have a choice of eight paths to follow. And let’s assume that you can’t see any real-purpose in any of the eight. THEN -- you MUST FIND A NINTH PATH."

This fits here pretty well - thanks for your input, it is appreciated.

**Comment by Byron** [comment]
> You probably have your own idea, but I would suggest cURL:
> 
> https://docs.rs/curl
> 
> I did some searching a while back, and I ended up choosing it because it had the lowest package footprint I could find

Absolutely, same here. It's the lowest-footprint solution to do http and https. `gitoxide` puts this functionality behind a trait, so other implementations can be added with relative ease in case there are advantages in avoiding curl in the future.

**Comment by nu8** [comment]
The obvious reason to avoid cURL is that its not Rust. But in my opinion all the pure Rust HTTPS clients are giant and bloated. If one exists that is smaller I would be interested though
