### ISSUE TITLE
`git-refs` MVP

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#90]
When writing any tool it's obvious that we really, really want to be able to resolve refs to objects.
We need to add the concept of `stores` right away as there are various types of them.

In typical repositories this requires the following:

* [x] factor zlib code into git-features, allowing different backends to be swapped with feature toggles.
* [x] split git-odb into stores and packs.
* A **loose file ref store** with the ability to
   * [x] find a single ref by partial name with algorithm of git
   * [x] initialize based on .git dir
   * and a loose reference type to
     * [x] resolve targets step by step
     * [x] peel it until an object is found
   * [x] do validation
   * [x] basic docs
* **git-repository**
   * [x] discover(…) to find git repos easily
* [ ] Update existing tools to use the new capability
   * experiments
      * [x] traversal
      * [x] diffing
      * [x] object-access
    * gixp
       * [x] organize
    * gix
       * [x] hours
    * [x] gitoxide-core
 * [x] better git-repository docs

### Out of scope

* [reftable] backend, which will be an addition to the existing `files` and `packed-refs` format.
* packed refs (handle peeled, fully peeled, sorted features)

[reftable]: https://github.com/git/git/commit/f675f2983809635ae8bd409ec04c9a87b79acb4c
[git-mit]: https://github.com/PurpleBooth/git-mit 

### Research

* [parse a loose ref](https://github.com/git/git/blob/de88ac70f3a801262eb3aa087e5d9a712be0a54a/refs/files-backend.c#L469)
* for parsing [`FETCH_HEAD` and `MERGE_HEAD`](https://github.com/git/git/blob/master/refs/files-backend.c#L469:L469)
* [instructions](https://github.com/git/git/blob/master/refs/refs-internal.h#L601:L602) with a lot of information on how refs are seen in git.
* [There are various backends](https://github.com/git/git/blob/master/refs/files-backend.c#L344) - files, packed, and an in-memory cache.

**Comment by kim** [comment]
Don't forget the reftable work (currently in [`seen`](https://github.com/git/git/commit/f675f2983809635ae8bd409ec04c9a87b79acb4c))!

_**/me** ducks_

**Comment by Byron** [comment]
Hehe, I won't for sure, for the MVP there can't be more than the basics though to help making the existing tools a bit less cumbersome.

It's an intermezzo between the juicy bits.

**Comment by kim** [comment]
> It's an intermezzo between the juicy bits.

Haha, yes of course.

I just thought I throw in the state of the series in `seen` here as some bedtime
reading. There are some subtle differences (locking comes to mind), which may be
interesting to keep in mind when designing the abstractions.

**Comment by Byron** [comment]
And what a reading it was, at least the 10% or so I got through before falling into a peaceful slumber.

For me thus far there are two learnings:

* ref-table is mutually exclusive to the files store even though it technically wouldn't have to be. Probably it's related with concurrent access to the repository.
* there is a lot going on to assure only one of these is selected and a repository configures that. It looks a bit like a dark science in code but I think in Rust there will be light.
* Google seems to have a  lot of refs since they appear to have contributed the implementation, and they have a much more readable style of writing C for sure. This will help when porting.

Another learning is that I am not good at counting ;).
