### ISSUE TITLE
gix: enable reusing of reqwest::blocking::Client

### ISSUE THREAD

**Issue by NobodyXu** [Byron/gitoxide#909]
### Summary 💡

It would be great if gix can configure fetching process to reuse existing reqwest::blocking::Client

### Motivation 🔦

This will enable:
 - Users to configure reqwest client, i.e. minimum tls version, etc
 - Reuse of reqwest connection pool

**Comment by Byron** [comment]
Thanks for chiming in .

However, I am closing this issue as it's not suitable as tracking issue in its current form, while it states something that's very well known to me: The `reqwest` backend will not see considerable amounts of work as there are other priorities, even though I agree that it would be nice to have a pure-Rust backend that is en-par with `curl` (`reqwest` or not).
