### ISSUE TITLE
gixp pack-create does not terminate on ctrl-c when reading from stdin

### ISSUE THREAD

**Issue by edward-shen** [Byron/gitoxide#92]
Repro steps:
 - `./gixp pack-create > /dev/null`

The global handler (from `git-features`) will respond correctly but the process will refuse to terminate until `EOF` (ctrl-d) is provided. 

I believe the "hanging" behavior is attributed to `.lines()` call in `gitoxide-core/pack/create.rs:L89` as that call will continue to read from the buffer until EOF. 

Not sure what the best solution is here, since the global handler implies it will terminate but it never actually does, but on the other hand this isn't quite a user facing tool, so they might realize they just need to send an EOF to stop it.

**Comment by Byron** [comment]
Please try again - it should work now.

**Comment by edward-shen** [comment]
LGTM!
