### ISSUE TITLE
`gix-tempfile` needs a new release

### ISSUE THREAD

**Issue by NobodyXu** [Byron/gitoxide#940]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

Currently, `gix` depends on `gix-tempfile` v7.0.0, which pulls in `gix-fs` v0.3.0 and pulls in `gix-features` v0.31

### Expected behavior 🤔

Release a new version of `gix-tempfile` which depends on `gix-fs` v0.4.0 and eliminates the old `gix-features` v0.31 dependency.

### Steps to reproduce 🕹

```
cargo tree -i gix-features@0.31.0
```

**Comment by Byron** [comment]
Thanks for letting me know! 
This stems from me finally not automatically publishing stable crates anymore, which as I learn now has this effect.

This means that in future, I have to make manual patch releases of these crates *or* adjust `cargo smart-release` to do that for me.

Closing, as I verified that the dependency duplication is now gone.
