### ISSUE TITLE
Redirects are not followed (at least with reqwest)

### ISSUE THREAD

**Issue by Jake-Shadle** [Byron/gitoxide#974]
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

When you fetch from a URL that redirects, the redirect does not seem to be followed and an error occurs. For example, in gitlab.com, all repository urls _must_ end with `.git`, otherwise they get redirected, as seen in the output from git itself.

```
% git clone https://gitlab.com/gilrs-project/gilrs
Cloning into 'gilrs'...
warning: redirecting to https://gitlab.com/gilrs-project/gilrs.git/
remote: Enumerating objects: 4667, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 4667 (delta 5), reused 12 (delta 0), pack-reused 4646
Receiving objects: 100% (4667/4667), 819.00 KiB | 3.72 MiB/s, done.
Resolving deltas: 100% (2962/2962), done.
```

Instead, at least with the reqwest backend (unsure about curl), this leads to an error

```
An IO error occurred when talking to the server: Received HTTP status 422
```

This error code is...wrong, but I don't know if that's a "this is how the git protocol does redirects" or just a gitlab oddity, but at least git understands it.

### Expected behavior 🤔

The redirect should be followed and the repo fetch successfully. In this case it's a trivial fix to just add the `.git` extension so that a redirect is not needed, but just given the status code this was not really clear until I did the same operation in git which printed out the above warning.

### Steps to reproduce 🕹

1. Attempt to clone `https://gitlab.com/gilrs-project/gilrs` with gix
2. Get I/O error with 422 status code

**Comment by Byron** [comment]
Indeed, it's a limitation of the `reqwest` based backend, which in many ways is nothing more than an MVP.
This works for the `curl` backend, for instance, which might also serve as example for how to implement this.

**Comment by Jake-Shadle** [comment]
Ahh ok, might take a look at that later then myself.

**Comment by NobodyXu** [comment]
[`reqwest::ClientBuilder::redirect`](https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.redirect) can be used to configure redirect behavior, by default it will follow redirects up to a maximum of 10.

[`reqwest::redirect::Policy`](https://docs.rs/reqwest/latest/reqwest/redirect/struct.Policy.html) provides several policies:
 - none
 - Set a `max` redirects allowed
 - Register a callback

@Byron If `gix` does not change the default, then maybe it's a good idea to raise the redirect limit to 20 or even 30.

**Comment by Byron** [comment]
Git makes this configurable to some extend, and the implementation [has to honour that](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpfollowRedirects).

**Comment by NobodyXu** [comment]
> Git makes this configurable to some extend, and the implementation [has to honour that](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpfollowRedirects).

The default is to only follow one redirect, however reqwest by default follows 10 redirects, so I think gix must has changed the default somewhere.

**Comment by Byron** [comment]
The crate isn't configuring this at all, but in order to work, it needs some integration the is visible in the curl crate. Namely, the redirected URL has to be made available to the caller which then will [validate it](https://github.com/Byron/gitoxide/blob/b057500dd3e6b75be3ebcd258cda0b946bedd9e1/gix-transport/src/client/blocking_io/http/curl/remote.rs#L355) and use the new base URL from that point on. Thus I am not surprised this doesn't work out of the box with a standard redirect as done by `reqwest`.

**Comment by NobodyXu** [comment]
Thanks for explanation, perhaps `gix` can explicitly issue a `get` using `reqwest` and then use [`reqwest::Response::url()`](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.url) to get the redirected url?

**Comment by Byron** [comment]
I am sure there is a way - you are welcome to try it in a PR and we take it from there.

**Comment by NobodyXu** [comment]
> I am sure there is a way - you are welcome to try it in a PR and we take it from there.

Sure, but can you give me a hint which crate should I modify?
I think `gix-transport` would have to be modified, but not sure about what other crates I need to modify.

**Comment by Byron** [comment]
That's correct, [it's all in `gix-transport`](https://github.com/Byron/gitoxide/blob/fadec775c5cd0532ab76802f56349cebc4a90d72/gix-transport/src/client/blocking_io/http/reqwest/remote.rs#L45). I recommend using the curl implementation as reference.

The value you'd need is [already available](https://github.com/Byron/gitoxide/blob/fadec775c5cd0532ab76802f56349cebc4a90d72/gix-transport/src/client/blocking_io/http/reqwest/remote.rs#L53) in the `reqwest` backend, and the only way to test it right now is to try `gix clone` by hand.
