### ISSUE TITLE
gix fails to recognize bare repos that have an index file as bare if they are not named `<repo>.git`

### ISSUE THREAD

**Issue by eatradish** [Byron/gitoxide#980]
### Current behavior 😯

My step:

```bash
gix clone --bare https://github.com/AOSC-Dev/oma oma-bare
mkdir oma-not-bare
cd oma-not-bare
git init
git --git-dir ../oma-bare --work-tree . checkout -f e8f56b5
cd ../oma-bare
gix fetch origin +refs/heads/*:refs/heads/*
```

`gix` return error:

```
Error: './.git/objects' wasn't a directory
```

### Expected behavior 🤔

`git` success to run:

```bash
$ git fetch origin +refs/heads/*:refs/heads/*
from https://github.com/AOSC-Dev/oma
 * [new branch]          cratify-oma -> cratify-oma
$ echo $?
0
```

**Comment by Byron** [comment]
Thanks for reporting! I can reproduce the issue and noticed that what matters here is the fact that a bare repository isn't called `repo.git`, but `repo-bare` in this case.

Apparently it's fooled into thinking the repo is indeed having a working tree, and goes off the rails from there.

**Comment by Byron** [comment]
This is fixed in `main`, please try again to validate. Thank you.

**Comment by Byron** [comment]
I could verify it with `gix` and the example provided here isn't reproducible anymore. Thanks again for sharing this case.

**Comment by eatradish** [comment]
Hi, I seem to have another problem after upgrading gitoxide to 0.29.0:

```
gix fetch origin +refs/heads/*:refs/heads/*
Error: Cannot find a remote for unborn branch
```

**Comment by eatradish** [comment]
HI, I seem to have another problem after upgrading gitoxide to 0.29.0:

```
$ gix fetch origin +refs/heads/*:refs/heads/*
Error: Cannot find a remote for unborn branch
```
